using Avalonia.Controls;
using Avalonia.Media;
using Avalonia.Media.Immutable;
using StellarAllegiance.Launcher.Flow;
using StellarAllegiance.Launcher.Theme;
using StellarAllegiance.Ui;
using GColor = Godot.Color;

namespace StellarAllegiance.Launcher.Theme;

// The launcher's counterpart of the game's UiKit: every colour, font and text style the UI uses comes
// from here, and everything here comes from the game's OWN DesignTokens.cs (compiled into
// launcher/Core through a Godot.Color shim — see Core/Theme/GodotColorShim.cs). There are deliberately
// no colour or size literals in the launcher's UI code: change a token in the game and the launcher
// follows on the next build. tests/LauncherTest lints for stray literals.
public static class Sa
{
    public static Color C(GColor c) => Color.FromUInt32(c.ToArgb32());

    public static IImmutableSolidColorBrush B(GColor c) => new ImmutableSolidColorBrush(C(c));

    // Godot's `new Color(from, alpha)` REPLACES the alpha — ported draw code relies on that.
    public static IImmutableSolidColorBrush B(GColor c, float alpha) =>
        new ImmutableSolidColorBrush(C(new GColor(c, alpha)));

    public static readonly IImmutableSolidColorBrush Void = B(DesignTokens.Void);
    public static readonly IImmutableSolidColorBrush Panel = B(DesignTokens.Panel);
    public static readonly IImmutableSolidColorBrush PanelDeep = B(DesignTokens.PanelDeep);
    public static readonly IImmutableSolidColorBrush PanelFill = B(DesignTokens.PanelFill);
    public static readonly IImmutableSolidColorBrush PanelSolid = B(DesignTokens.PanelSolid);
    public static readonly IImmutableSolidColorBrush Well = B(DesignTokens.Well);
    public static readonly IImmutableSolidColorBrush Scrim = B(DesignTokens.Scrim);
    public static readonly IImmutableSolidColorBrush BorderHi = B(DesignTokens.BorderHi);
    public static readonly IImmutableSolidColorBrush BorderMid = B(DesignTokens.BorderMid);
    public static readonly IImmutableSolidColorBrush BorderLo = B(DesignTokens.BorderLo);
    public static readonly IImmutableSolidColorBrush Accent = B(DesignTokens.TeamAccent);
    public static readonly IImmutableSolidColorBrush TextHi = B(DesignTokens.TextHi);
    public static readonly IImmutableSolidColorBrush Text2 = B(DesignTokens.Text2);
    public static readonly IImmutableSolidColorBrush TextDim = B(DesignTokens.TextDim);
    public static readonly IImmutableSolidColorBrush Ok = B(DesignTokens.Ok);
    public static readonly IImmutableSolidColorBrush Warn = B(DesignTokens.Warn);
    public static readonly IImmutableSolidColorBrush Danger = B(DesignTokens.Danger);
    public static readonly IImmutableSolidColorBrush DangerText = B(DesignTokens.DangerText);
    public static readonly IImmutableSolidColorBrush Data = B(DesignTokens.Data);

    // Static font instances generated by tools/font-instancer (Avalonia cannot drive variable-font axes,
    // and Saira's default weight is Thin). The avares:// scope pins lookups to the embedded files, so a
    // system-installed JetBrains Mono can never shadow ours.
    public static readonly FontFamily Saira = new("avares://StellarLauncher/Assets/Fonts#Saira");
    public static readonly FontFamily Mono = new("avares://StellarLauncher/Assets/Fonts#JetBrains Mono");

    // Same mapping as the game's StatusPill kinds (client/scripts/ui/DataFeedback.cs).
    public static GColor ToneColor(Tone tone) =>
        tone switch
        {
            Tone.Ok => DesignTokens.Ok,
            Tone.Warn => DesignTokens.Warn,
            Tone.Danger => DesignTokens.Danger,
            Tone.Accent => DesignTokens.TeamAccent,
            _ => DesignTokens.Text2,
        };

    // The launcher's UiKit.MakeLabel: font, weight, size, colour and letter spacing all come from the
    // shared TextStyleTable (drift-tested against the game's UiKit.cs). Like the game, the Label style
    // does NOT upper-case for you — callers pass caps text.
    public static TextBlock Text(string text, TextStyle style, GColor? color = null, int? size = null)
    {
        var spec = TextStyleTable.Get(style);
        var block = new TextBlock
        {
            Text = text,
            FontFamily = spec.Family == FontFamilyKind.Mono ? Mono : Saira,
            FontWeight = (FontWeight)spec.Weight,
            FontSize = size ?? spec.SizePx,
            Foreground = B(color ?? spec.Color),
            LetterSpacing = spec.LetterSpacing,
        };
        if (spec.Family == FontFamilyKind.Mono)
            block.FontFeatures = NoLigatures; // `->` and `!=` must stay two characters in a telemetry readout
        return block;
    }

    // JetBrains Mono draws its arrows/operators through `calt`; `liga` is switched off for good measure.
    public static readonly FontFeatureCollection NoLigatures = [FontFeature.Parse("-liga"), FontFeature.Parse("-calt")];
}
