// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AlephHandle : RemoteTableHandle<EventContext, Aleph>
        {
            protected override string RemoteTableName => "aleph";

            public sealed class AlephIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Aleph row) => row.AlephId;

                public AlephIdUniqueIndex(AlephHandle table) : base(table) { }
            }

            public readonly AlephIdUniqueIndex AlephId;

            internal AlephHandle(DbConnection conn) : base(conn)
            {
                AlephId = new(this);
            }

            protected override object GetPrimaryKey(Aleph row) => row.AlephId;
        }

        public readonly AlephHandle Aleph;
    }

    public sealed class AlephCols
    {
        public global::SpacetimeDB.Col<Aleph, ulong> AlephId { get; }
        public global::SpacetimeDB.Col<Aleph, uint> SectorId { get; }
        public global::SpacetimeDB.Col<Aleph, ulong> PartnerId { get; }
        public global::SpacetimeDB.Col<Aleph, uint> DestSectorId { get; }
        public global::SpacetimeDB.Col<Aleph, float> PosX { get; }
        public global::SpacetimeDB.Col<Aleph, float> PosY { get; }
        public global::SpacetimeDB.Col<Aleph, float> PosZ { get; }

        public AlephCols(string tableName)
        {
            AlephId = new global::SpacetimeDB.Col<Aleph, ulong>(tableName, "aleph_id");
            SectorId = new global::SpacetimeDB.Col<Aleph, uint>(tableName, "sector_id");
            PartnerId = new global::SpacetimeDB.Col<Aleph, ulong>(tableName, "partner_id");
            DestSectorId = new global::SpacetimeDB.Col<Aleph, uint>(tableName, "dest_sector_id");
            PosX = new global::SpacetimeDB.Col<Aleph, float>(tableName, "pos_x");
            PosY = new global::SpacetimeDB.Col<Aleph, float>(tableName, "pos_y");
            PosZ = new global::SpacetimeDB.Col<Aleph, float>(tableName, "pos_z");
        }
    }

    public sealed class AlephIxCols
    {
        public global::SpacetimeDB.IxCol<Aleph, ulong> AlephId { get; }

        public AlephIxCols(string tableName)
        {
            AlephId = new global::SpacetimeDB.IxCol<Aleph, ulong>(tableName, "aleph_id");
        }
    }
}
