// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AsteroidHandle : RemoteTableHandle<EventContext, Asteroid>
        {
            protected override string RemoteTableName => "asteroid";

            public sealed class AsteroidIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Asteroid row) => row.AsteroidId;

                public AsteroidIdUniqueIndex(AsteroidHandle table) : base(table) { }
            }

            public readonly AsteroidIdUniqueIndex AsteroidId;

            public sealed class SectorIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(Asteroid row) => row.SectorId;

                public SectorIdIndex(AsteroidHandle table) : base(table) { }
            }

            public readonly SectorIdIndex SectorId;

            internal AsteroidHandle(DbConnection conn) : base(conn)
            {
                AsteroidId = new(this);
                SectorId = new(this);
            }

            protected override object GetPrimaryKey(Asteroid row) => row.AsteroidId;
        }

        public readonly AsteroidHandle Asteroid;
    }

    public sealed class AsteroidCols
    {
        public global::SpacetimeDB.Col<Asteroid, ulong> AsteroidId { get; }
        public global::SpacetimeDB.Col<Asteroid, uint> SectorId { get; }
        public global::SpacetimeDB.Col<Asteroid, float> PosX { get; }
        public global::SpacetimeDB.Col<Asteroid, float> PosY { get; }
        public global::SpacetimeDB.Col<Asteroid, float> PosZ { get; }
        public global::SpacetimeDB.Col<Asteroid, float> Radius { get; }
        public global::SpacetimeDB.Col<Asteroid, string> Variant { get; }
        public global::SpacetimeDB.Col<Asteroid, float> RotX { get; }
        public global::SpacetimeDB.Col<Asteroid, float> RotY { get; }
        public global::SpacetimeDB.Col<Asteroid, float> RotZ { get; }

        public AsteroidCols(string tableName)
        {
            AsteroidId = new global::SpacetimeDB.Col<Asteroid, ulong>(tableName, "asteroid_id");
            SectorId = new global::SpacetimeDB.Col<Asteroid, uint>(tableName, "sector_id");
            PosX = new global::SpacetimeDB.Col<Asteroid, float>(tableName, "pos_x");
            PosY = new global::SpacetimeDB.Col<Asteroid, float>(tableName, "pos_y");
            PosZ = new global::SpacetimeDB.Col<Asteroid, float>(tableName, "pos_z");
            Radius = new global::SpacetimeDB.Col<Asteroid, float>(tableName, "radius");
            Variant = new global::SpacetimeDB.Col<Asteroid, string>(tableName, "variant");
            RotX = new global::SpacetimeDB.Col<Asteroid, float>(tableName, "rot_x");
            RotY = new global::SpacetimeDB.Col<Asteroid, float>(tableName, "rot_y");
            RotZ = new global::SpacetimeDB.Col<Asteroid, float>(tableName, "rot_z");
        }
    }

    public sealed class AsteroidIxCols
    {
        public global::SpacetimeDB.IxCol<Asteroid, ulong> AsteroidId { get; }
        public global::SpacetimeDB.IxCol<Asteroid, uint> SectorId { get; }

        public AsteroidIxCols(string tableName)
        {
            AsteroidId = new global::SpacetimeDB.IxCol<Asteroid, ulong>(tableName, "asteroid_id");
            SectorId = new global::SpacetimeDB.IxCol<Asteroid, uint>(tableName, "sector_id");
        }
    }
}
