// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BaseHandle : RemoteTableHandle<EventContext, Base>
        {
            protected override string RemoteTableName => "base";

            public sealed class BaseIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Base row) => row.BaseId;

                public BaseIdUniqueIndex(BaseHandle table) : base(table) { }
            }

            public readonly BaseIdUniqueIndex BaseId;

            internal BaseHandle(DbConnection conn) : base(conn)
            {
                BaseId = new(this);
            }

            protected override object GetPrimaryKey(Base row) => row.BaseId;
        }

        public readonly BaseHandle Base;
    }

    public sealed class BaseCols
    {
        public global::SpacetimeDB.Col<Base, ulong> BaseId { get; }
        public global::SpacetimeDB.Col<Base, byte> Team { get; }
        public global::SpacetimeDB.Col<Base, uint> SectorId { get; }
        public global::SpacetimeDB.Col<Base, float> PosX { get; }
        public global::SpacetimeDB.Col<Base, float> PosY { get; }
        public global::SpacetimeDB.Col<Base, float> PosZ { get; }
        public global::SpacetimeDB.Col<Base, float> Health { get; }

        public BaseCols(string tableName)
        {
            BaseId = new global::SpacetimeDB.Col<Base, ulong>(tableName, "base_id");
            Team = new global::SpacetimeDB.Col<Base, byte>(tableName, "team");
            SectorId = new global::SpacetimeDB.Col<Base, uint>(tableName, "sector_id");
            PosX = new global::SpacetimeDB.Col<Base, float>(tableName, "pos_x");
            PosY = new global::SpacetimeDB.Col<Base, float>(tableName, "pos_y");
            PosZ = new global::SpacetimeDB.Col<Base, float>(tableName, "pos_z");
            Health = new global::SpacetimeDB.Col<Base, float>(tableName, "health");
        }
    }

    public sealed class BaseIxCols
    {
        public global::SpacetimeDB.IxCol<Base, ulong> BaseId { get; }

        public BaseIxCols(string tableName)
        {
            BaseId = new global::SpacetimeDB.IxCol<Base, ulong>(tableName, "base_id");
        }
    }
}
