// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BaseDefHandle : RemoteTableHandle<EventContext, BaseDef>
        {
            protected override string RemoteTableName => "base_def";

            public sealed class BaseTypeIdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(BaseDef row) => row.BaseTypeId;

                public BaseTypeIdUniqueIndex(BaseDefHandle table) : base(table) { }
            }

            public readonly BaseTypeIdUniqueIndex BaseTypeId;

            internal BaseDefHandle(DbConnection conn) : base(conn)
            {
                BaseTypeId = new(this);
            }

            protected override object GetPrimaryKey(BaseDef row) => row.BaseTypeId;
        }

        public readonly BaseDefHandle BaseDef;
    }

    public sealed class BaseDefCols
    {
        public global::SpacetimeDB.Col<BaseDef, byte> BaseTypeId { get; }
        public global::SpacetimeDB.Col<BaseDef, string> Name { get; }
        public global::SpacetimeDB.Col<BaseDef, float> Radius { get; }
        public global::SpacetimeDB.Col<BaseDef, float> MaxHealth { get; }
        public global::SpacetimeDB.Col<BaseDef, System.Collections.Generic.List<HardpointDef>> Hardpoints { get; }

        public BaseDefCols(string tableName)
        {
            BaseTypeId = new global::SpacetimeDB.Col<BaseDef, byte>(tableName, "base_type_id");
            Name = new global::SpacetimeDB.Col<BaseDef, string>(tableName, "name");
            Radius = new global::SpacetimeDB.Col<BaseDef, float>(tableName, "radius");
            MaxHealth = new global::SpacetimeDB.Col<BaseDef, float>(tableName, "max_health");
            Hardpoints = new global::SpacetimeDB.Col<BaseDef, System.Collections.Generic.List<HardpointDef>>(tableName, "hardpoints");
        }
    }

    public sealed class BaseDefIxCols
    {
        public global::SpacetimeDB.IxCol<BaseDef, byte> BaseTypeId { get; }

        public BaseDefIxCols(string tableName)
        {
            BaseTypeId = new global::SpacetimeDB.IxCol<BaseDef, byte>(tableName, "base_type_id");
        }
    }
}
