// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ChatMessageHandle : RemoteTableHandle<EventContext, ChatMessage>
        {
            protected override string RemoteTableName => "chat_message";

            public sealed class MessageIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ChatMessage row) => row.MessageId;

                public MessageIdUniqueIndex(ChatMessageHandle table) : base(table) { }
            }

            public readonly MessageIdUniqueIndex MessageId;

            internal ChatMessageHandle(DbConnection conn) : base(conn)
            {
                MessageId = new(this);
            }

            protected override object GetPrimaryKey(ChatMessage row) => row.MessageId;
        }

        public readonly ChatMessageHandle ChatMessage;
    }

    public sealed class ChatMessageCols
    {
        public global::SpacetimeDB.Col<ChatMessage, ulong> MessageId { get; }
        public global::SpacetimeDB.Col<ChatMessage, SpacetimeDB.Identity> Sender { get; }
        public global::SpacetimeDB.Col<ChatMessage, string> SenderName { get; }
        public global::SpacetimeDB.Col<ChatMessage, byte> Scope { get; }
        public global::SpacetimeDB.Col<ChatMessage, byte> Team { get; }
        public global::SpacetimeDB.Col<ChatMessage, SpacetimeDB.Identity> Recipient { get; }
        public global::SpacetimeDB.Col<ChatMessage, bool> IsSystem { get; }
        public global::SpacetimeDB.Col<ChatMessage, string> Text { get; }
        public global::SpacetimeDB.Col<ChatMessage, SpacetimeDB.Timestamp> CreatedAt { get; }

        public ChatMessageCols(string tableName)
        {
            MessageId = new global::SpacetimeDB.Col<ChatMessage, ulong>(tableName, "message_id");
            Sender = new global::SpacetimeDB.Col<ChatMessage, SpacetimeDB.Identity>(tableName, "sender");
            SenderName = new global::SpacetimeDB.Col<ChatMessage, string>(tableName, "sender_name");
            Scope = new global::SpacetimeDB.Col<ChatMessage, byte>(tableName, "scope");
            Team = new global::SpacetimeDB.Col<ChatMessage, byte>(tableName, "team");
            Recipient = new global::SpacetimeDB.Col<ChatMessage, SpacetimeDB.Identity>(tableName, "recipient");
            IsSystem = new global::SpacetimeDB.Col<ChatMessage, bool>(tableName, "is_system");
            Text = new global::SpacetimeDB.Col<ChatMessage, string>(tableName, "text");
            CreatedAt = new global::SpacetimeDB.Col<ChatMessage, SpacetimeDB.Timestamp>(tableName, "created_at");
        }
    }

    public sealed class ChatMessageIxCols
    {
        public global::SpacetimeDB.IxCol<ChatMessage, ulong> MessageId { get; }

        public ChatMessageIxCols(string tableName)
        {
            MessageId = new global::SpacetimeDB.IxCol<ChatMessage, ulong>(tableName, "message_id");
        }
    }
}
