// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class JoinTokenHandle : RemoteTableHandle<EventContext, JoinToken>
        {
            protected override string RemoteTableName => "join_token";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(JoinToken row) => row.Identity;

                public IdentityUniqueIndex(JoinTokenHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal JoinTokenHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(JoinToken row) => row.Identity;
        }

        public readonly JoinTokenHandle JoinToken;
    }

    public sealed class JoinTokenCols
    {
        public global::SpacetimeDB.Col<JoinToken, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<JoinToken, byte> Team { get; }
        public global::SpacetimeDB.Col<JoinToken, string> Token { get; }

        public JoinTokenCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<JoinToken, SpacetimeDB.Identity>(tableName, "identity");
            Team = new global::SpacetimeDB.Col<JoinToken, byte>(tableName, "team");
            Token = new global::SpacetimeDB.Col<JoinToken, string>(tableName, "token");
        }
    }

    public sealed class JoinTokenIxCols
    {
        public global::SpacetimeDB.IxCol<JoinToken, SpacetimeDB.Identity> Identity { get; }

        public JoinTokenIxCols(string tableName)
        {
            Identity = new global::SpacetimeDB.IxCol<JoinToken, SpacetimeDB.Identity>(tableName, "identity");
        }
    }
}
