// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MatchHandle : RemoteTableHandle<EventContext, Match>
        {
            protected override string RemoteTableName => "match";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Match row) => row.Id;

                public IdUniqueIndex(MatchHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal MatchHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Match row) => row.Id;
        }

        public readonly MatchHandle Match;
    }

    public sealed class MatchCols
    {
        public global::SpacetimeDB.Col<Match, uint> Id { get; }
        public global::SpacetimeDB.Col<Match, uint> Tick { get; }
        public global::SpacetimeDB.Col<Match, MatchPhase> Phase { get; }
        public global::SpacetimeDB.Col<Match, byte> Winner { get; }
        public global::SpacetimeDB.Col<Match, byte> EngagedTeams { get; }
        public global::SpacetimeDB.Col<Match, ulong> Seed { get; }
        public global::SpacetimeDB.Col<Match, ulong> Epoch { get; }

        public MatchCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<Match, uint>(tableName, "id");
            Tick = new global::SpacetimeDB.Col<Match, uint>(tableName, "tick");
            Phase = new global::SpacetimeDB.Col<Match, MatchPhase>(tableName, "phase");
            Winner = new global::SpacetimeDB.Col<Match, byte>(tableName, "winner");
            EngagedTeams = new global::SpacetimeDB.Col<Match, byte>(tableName, "engaged_teams");
            Seed = new global::SpacetimeDB.Col<Match, ulong>(tableName, "seed");
            Epoch = new global::SpacetimeDB.Col<Match, ulong>(tableName, "epoch");
        }
    }

    public sealed class MatchIxCols
    {
        public global::SpacetimeDB.IxCol<Match, uint> Id { get; }

        public MatchIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<Match, uint>(tableName, "id");
        }
    }
}
