// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PigHandle : RemoteTableHandle<EventContext, Pig>
        {
            protected override string RemoteTableName => "pig";

            public sealed class PigIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Pig row) => row.PigId;

                public PigIdUniqueIndex(PigHandle table) : base(table) { }
            }

            public readonly PigIdUniqueIndex PigId;

            internal PigHandle(DbConnection conn) : base(conn)
            {
                PigId = new(this);
            }

            protected override object GetPrimaryKey(Pig row) => row.PigId;
        }

        public readonly PigHandle Pig;
    }

    public sealed class PigCols
    {
        public global::SpacetimeDB.Col<Pig, ulong> PigId { get; }
        public global::SpacetimeDB.Col<Pig, byte> Team { get; }
        public global::SpacetimeDB.Col<Pig, ShipClass> Class { get; }
        public global::SpacetimeDB.Col<Pig, ulong> ShipId { get; }
        public global::SpacetimeDB.Col<Pig, uint> RespawnAtTick { get; }
        public global::SpacetimeDB.Col<Pig, PigState> State { get; }
        public global::SpacetimeDB.Col<Pig, ulong> TargetShipId { get; }

        public PigCols(string tableName)
        {
            PigId = new global::SpacetimeDB.Col<Pig, ulong>(tableName, "pig_id");
            Team = new global::SpacetimeDB.Col<Pig, byte>(tableName, "team");
            Class = new global::SpacetimeDB.Col<Pig, ShipClass>(tableName, "class");
            ShipId = new global::SpacetimeDB.Col<Pig, ulong>(tableName, "ship_id");
            RespawnAtTick = new global::SpacetimeDB.Col<Pig, uint>(tableName, "respawn_at_tick");
            State = new global::SpacetimeDB.Col<Pig, PigState>(tableName, "state");
            TargetShipId = new global::SpacetimeDB.Col<Pig, ulong>(tableName, "target_ship_id");
        }
    }

    public sealed class PigIxCols
    {
        public global::SpacetimeDB.IxCol<Pig, ulong> PigId { get; }

        public PigIxCols(string tableName)
        {
            PigId = new global::SpacetimeDB.IxCol<Pig, ulong>(tableName, "pig_id");
        }
    }
}
