// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PigBrainTimerHandle : RemoteTableHandle<EventContext, PigBrainTimer>
        {
            protected override string RemoteTableName => "pig_brain_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PigBrainTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(PigBrainTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal PigBrainTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(PigBrainTimer row) => row.ScheduledId;
        }

        public readonly PigBrainTimerHandle PigBrainTimer;
    }

    public sealed class PigBrainTimerCols
    {
        public global::SpacetimeDB.Col<PigBrainTimer, ulong> ScheduledId { get; }
        public global::SpacetimeDB.Col<PigBrainTimer, SpacetimeDB.ScheduleAt> ScheduledAt { get; }

        public PigBrainTimerCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.Col<PigBrainTimer, ulong>(tableName, "scheduled_id");
            ScheduledAt = new global::SpacetimeDB.Col<PigBrainTimer, SpacetimeDB.ScheduleAt>(tableName, "scheduled_at");
        }
    }

    public sealed class PigBrainTimerIxCols
    {
        public global::SpacetimeDB.IxCol<PigBrainTimer, ulong> ScheduledId { get; }

        public PigBrainTimerIxCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.IxCol<PigBrainTimer, ulong>(tableName, "scheduled_id");
        }
    }
}
