// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PigSquadHandle : RemoteTableHandle<EventContext, PigSquad>
        {
            protected override string RemoteTableName => "pig_squad";

            public sealed class TeamUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(PigSquad row) => row.Team;

                public TeamUniqueIndex(PigSquadHandle table) : base(table) { }
            }

            public readonly TeamUniqueIndex Team;

            internal PigSquadHandle(DbConnection conn) : base(conn)
            {
                Team = new(this);
            }

            protected override object GetPrimaryKey(PigSquad row) => row.Team;
        }

        public readonly PigSquadHandle PigSquad;
    }

    public sealed class PigSquadCols
    {
        public global::SpacetimeDB.Col<PigSquad, byte> Team { get; }
        public global::SpacetimeDB.Col<PigSquad, uint> NextSquadTick { get; }
        public global::SpacetimeDB.Col<PigSquad, bool> Active { get; }

        public PigSquadCols(string tableName)
        {
            Team = new global::SpacetimeDB.Col<PigSquad, byte>(tableName, "team");
            NextSquadTick = new global::SpacetimeDB.Col<PigSquad, uint>(tableName, "next_squad_tick");
            Active = new global::SpacetimeDB.Col<PigSquad, bool>(tableName, "active");
        }
    }

    public sealed class PigSquadIxCols
    {
        public global::SpacetimeDB.IxCol<PigSquad, byte> Team { get; }

        public PigSquadIxCols(string tableName)
        {
            Team = new global::SpacetimeDB.IxCol<PigSquad, byte>(tableName, "team");
        }
    }
}
