// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerHandle : RemoteTableHandle<EventContext, Player>
        {
            protected override string RemoteTableName => "player";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Player row) => row.Identity;

                public IdentityUniqueIndex(PlayerHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal PlayerHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(Player row) => row.Identity;
        }

        public readonly PlayerHandle Player;
    }

    public sealed class PlayerCols
    {
        public global::SpacetimeDB.Col<Player, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<Player, byte> Team { get; }
        public global::SpacetimeDB.Col<Player, ulong> ShipId { get; }
        public global::SpacetimeDB.Col<Player, bool> Online { get; }
        public global::SpacetimeDB.Col<Player, string> Name { get; }

        public PlayerCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<Player, SpacetimeDB.Identity>(tableName, "identity");
            Team = new global::SpacetimeDB.Col<Player, byte>(tableName, "team");
            ShipId = new global::SpacetimeDB.Col<Player, ulong>(tableName, "ship_id");
            Online = new global::SpacetimeDB.Col<Player, bool>(tableName, "online");
            Name = new global::SpacetimeDB.Col<Player, string>(tableName, "name");
        }
    }

    public sealed class PlayerIxCols
    {
        public global::SpacetimeDB.IxCol<Player, SpacetimeDB.Identity> Identity { get; }

        public PlayerIxCols(string tableName)
        {
            Identity = new global::SpacetimeDB.IxCol<Player, SpacetimeDB.Identity>(tableName, "identity");
        }
    }
}
