// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ProjectileHandle : RemoteTableHandle<EventContext, Projectile>
        {
            protected override string RemoteTableName => "projectile";

            public sealed class ProjectileIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Projectile row) => row.ProjectileId;

                public ProjectileIdUniqueIndex(ProjectileHandle table) : base(table) { }
            }

            public readonly ProjectileIdUniqueIndex ProjectileId;

            internal ProjectileHandle(DbConnection conn) : base(conn)
            {
                ProjectileId = new(this);
            }

            protected override object GetPrimaryKey(Projectile row) => row.ProjectileId;
        }

        public readonly ProjectileHandle Projectile;
    }

    public sealed class ProjectileCols
    {
        public global::SpacetimeDB.Col<Projectile, ulong> ProjectileId { get; }
        public global::SpacetimeDB.Col<Projectile, byte> Team { get; }
        public global::SpacetimeDB.Col<Projectile, uint> SectorId { get; }
        public global::SpacetimeDB.Col<Projectile, float> Damage { get; }
        public global::SpacetimeDB.Col<Projectile, float> PosX { get; }
        public global::SpacetimeDB.Col<Projectile, float> PosY { get; }
        public global::SpacetimeDB.Col<Projectile, float> PosZ { get; }
        public global::SpacetimeDB.Col<Projectile, float> VelX { get; }
        public global::SpacetimeDB.Col<Projectile, float> VelY { get; }
        public global::SpacetimeDB.Col<Projectile, float> VelZ { get; }
        public global::SpacetimeDB.Col<Projectile, uint> SpawnTick { get; }
        public global::SpacetimeDB.Col<Projectile, uint> ExpiresAtTick { get; }
        public global::SpacetimeDB.Col<Projectile, bool> FromPig { get; }

        public ProjectileCols(string tableName)
        {
            ProjectileId = new global::SpacetimeDB.Col<Projectile, ulong>(tableName, "projectile_id");
            Team = new global::SpacetimeDB.Col<Projectile, byte>(tableName, "team");
            SectorId = new global::SpacetimeDB.Col<Projectile, uint>(tableName, "sector_id");
            Damage = new global::SpacetimeDB.Col<Projectile, float>(tableName, "damage");
            PosX = new global::SpacetimeDB.Col<Projectile, float>(tableName, "pos_x");
            PosY = new global::SpacetimeDB.Col<Projectile, float>(tableName, "pos_y");
            PosZ = new global::SpacetimeDB.Col<Projectile, float>(tableName, "pos_z");
            VelX = new global::SpacetimeDB.Col<Projectile, float>(tableName, "vel_x");
            VelY = new global::SpacetimeDB.Col<Projectile, float>(tableName, "vel_y");
            VelZ = new global::SpacetimeDB.Col<Projectile, float>(tableName, "vel_z");
            SpawnTick = new global::SpacetimeDB.Col<Projectile, uint>(tableName, "spawn_tick");
            ExpiresAtTick = new global::SpacetimeDB.Col<Projectile, uint>(tableName, "expires_at_tick");
            FromPig = new global::SpacetimeDB.Col<Projectile, bool>(tableName, "from_pig");
        }
    }

    public sealed class ProjectileIxCols
    {
        public global::SpacetimeDB.IxCol<Projectile, ulong> ProjectileId { get; }

        public ProjectileIxCols(string tableName)
        {
            ProjectileId = new global::SpacetimeDB.IxCol<Projectile, ulong>(tableName, "projectile_id");
        }
    }
}
