// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SectorHandle : RemoteTableHandle<EventContext, Sector>
        {
            protected override string RemoteTableName => "sector";

            public sealed class SectorIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Sector row) => row.SectorId;

                public SectorIdUniqueIndex(SectorHandle table) : base(table) { }
            }

            public readonly SectorIdUniqueIndex SectorId;

            internal SectorHandle(DbConnection conn) : base(conn)
            {
                SectorId = new(this);
            }

            protected override object GetPrimaryKey(Sector row) => row.SectorId;
        }

        public readonly SectorHandle Sector;
    }

    public sealed class SectorCols
    {
        public global::SpacetimeDB.Col<Sector, uint> SectorId { get; }
        public global::SpacetimeDB.Col<Sector, string> Name { get; }
        public global::SpacetimeDB.Col<Sector, float> CenterX { get; }
        public global::SpacetimeDB.Col<Sector, float> CenterY { get; }
        public global::SpacetimeDB.Col<Sector, float> CenterZ { get; }
        public global::SpacetimeDB.Col<Sector, float> Radius { get; }

        public SectorCols(string tableName)
        {
            SectorId = new global::SpacetimeDB.Col<Sector, uint>(tableName, "sector_id");
            Name = new global::SpacetimeDB.Col<Sector, string>(tableName, "name");
            CenterX = new global::SpacetimeDB.Col<Sector, float>(tableName, "center_x");
            CenterY = new global::SpacetimeDB.Col<Sector, float>(tableName, "center_y");
            CenterZ = new global::SpacetimeDB.Col<Sector, float>(tableName, "center_z");
            Radius = new global::SpacetimeDB.Col<Sector, float>(tableName, "radius");
        }
    }

    public sealed class SectorIxCols
    {
        public global::SpacetimeDB.IxCol<Sector, uint> SectorId { get; }

        public SectorIxCols(string tableName)
        {
            SectorId = new global::SpacetimeDB.IxCol<Sector, uint>(tableName, "sector_id");
        }
    }
}
