// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ShipClassDefHandle : RemoteTableHandle<EventContext, ShipClassDef>
        {
            protected override string RemoteTableName => "ship_class_def";

            public sealed class ClassIdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(ShipClassDef row) => row.ClassId;

                public ClassIdUniqueIndex(ShipClassDefHandle table) : base(table) { }
            }

            public readonly ClassIdUniqueIndex ClassId;

            internal ShipClassDefHandle(DbConnection conn) : base(conn)
            {
                ClassId = new(this);
            }

            protected override object GetPrimaryKey(ShipClassDef row) => row.ClassId;
        }

        public readonly ShipClassDefHandle ShipClassDef;
    }

    public sealed class ShipClassDefCols
    {
        public global::SpacetimeDB.Col<ShipClassDef, byte> ClassId { get; }
        public global::SpacetimeDB.Col<ShipClassDef, string> Name { get; }
        public global::SpacetimeDB.Col<ShipClassDef, float> Mass { get; }
        public global::SpacetimeDB.Col<ShipClassDef, float> MaxSpeed { get; }
        public global::SpacetimeDB.Col<ShipClassDef, float> Accel { get; }
        public global::SpacetimeDB.Col<ShipClassDef, float> RateYawDeg { get; }
        public global::SpacetimeDB.Col<ShipClassDef, float> RatePitchDeg { get; }
        public global::SpacetimeDB.Col<ShipClassDef, float> RateRollDeg { get; }
        public global::SpacetimeDB.Col<ShipClassDef, float> DriftYawDeg { get; }
        public global::SpacetimeDB.Col<ShipClassDef, float> DriftPitchDeg { get; }
        public global::SpacetimeDB.Col<ShipClassDef, float> SideMult { get; }
        public global::SpacetimeDB.Col<ShipClassDef, float> BackMult { get; }
        public global::SpacetimeDB.Col<ShipClassDef, float> AbAccel { get; }
        public global::SpacetimeDB.Col<ShipClassDef, float> AbOnRate { get; }
        public global::SpacetimeDB.Col<ShipClassDef, float> AbOffRate { get; }
        public global::SpacetimeDB.Col<ShipClassDef, float> MaxHull { get; }
        public global::SpacetimeDB.Col<ShipClassDef, System.Collections.Generic.List<HardpointDef>> Hardpoints { get; }
        public global::SpacetimeDB.Col<ShipClassDef, uint> FactionId { get; }

        public ShipClassDefCols(string tableName)
        {
            ClassId = new global::SpacetimeDB.Col<ShipClassDef, byte>(tableName, "class_id");
            Name = new global::SpacetimeDB.Col<ShipClassDef, string>(tableName, "name");
            Mass = new global::SpacetimeDB.Col<ShipClassDef, float>(tableName, "mass");
            MaxSpeed = new global::SpacetimeDB.Col<ShipClassDef, float>(tableName, "max_speed");
            Accel = new global::SpacetimeDB.Col<ShipClassDef, float>(tableName, "accel");
            RateYawDeg = new global::SpacetimeDB.Col<ShipClassDef, float>(tableName, "rate_yaw_deg");
            RatePitchDeg = new global::SpacetimeDB.Col<ShipClassDef, float>(tableName, "rate_pitch_deg");
            RateRollDeg = new global::SpacetimeDB.Col<ShipClassDef, float>(tableName, "rate_roll_deg");
            DriftYawDeg = new global::SpacetimeDB.Col<ShipClassDef, float>(tableName, "drift_yaw_deg");
            DriftPitchDeg = new global::SpacetimeDB.Col<ShipClassDef, float>(tableName, "drift_pitch_deg");
            SideMult = new global::SpacetimeDB.Col<ShipClassDef, float>(tableName, "side_mult");
            BackMult = new global::SpacetimeDB.Col<ShipClassDef, float>(tableName, "back_mult");
            AbAccel = new global::SpacetimeDB.Col<ShipClassDef, float>(tableName, "ab_accel");
            AbOnRate = new global::SpacetimeDB.Col<ShipClassDef, float>(tableName, "ab_on_rate");
            AbOffRate = new global::SpacetimeDB.Col<ShipClassDef, float>(tableName, "ab_off_rate");
            MaxHull = new global::SpacetimeDB.Col<ShipClassDef, float>(tableName, "max_hull");
            Hardpoints = new global::SpacetimeDB.Col<ShipClassDef, System.Collections.Generic.List<HardpointDef>>(tableName, "hardpoints");
            FactionId = new global::SpacetimeDB.Col<ShipClassDef, uint>(tableName, "faction_id");
        }
    }

    public sealed class ShipClassDefIxCols
    {
        public global::SpacetimeDB.IxCol<ShipClassDef, byte> ClassId { get; }

        public ShipClassDefIxCols(string tableName)
        {
            ClassId = new global::SpacetimeDB.IxCol<ShipClassDef, byte>(tableName, "class_id");
        }
    }
}
