// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ShipInputHandle : RemoteTableHandle<EventContext, ShipInput>
        {
            protected override string RemoteTableName => "ship_input";

            public sealed class ShipIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ShipInput row) => row.ShipId;

                public ShipIdUniqueIndex(ShipInputHandle table) : base(table) { }
            }

            public readonly ShipIdUniqueIndex ShipId;

            internal ShipInputHandle(DbConnection conn) : base(conn)
            {
                ShipId = new(this);
            }

            protected override object GetPrimaryKey(ShipInput row) => row.ShipId;
        }

        public readonly ShipInputHandle ShipInput;
    }

    public sealed class ShipInputCols
    {
        public global::SpacetimeDB.Col<ShipInput, ulong> ShipId { get; }
        public global::SpacetimeDB.Col<ShipInput, float> Thrust { get; }
        public global::SpacetimeDB.Col<ShipInput, float> StrafeX { get; }
        public global::SpacetimeDB.Col<ShipInput, float> StrafeY { get; }
        public global::SpacetimeDB.Col<ShipInput, float> Yaw { get; }
        public global::SpacetimeDB.Col<ShipInput, float> Pitch { get; }
        public global::SpacetimeDB.Col<ShipInput, float> Roll { get; }
        public global::SpacetimeDB.Col<ShipInput, bool> Firing { get; }
        public global::SpacetimeDB.Col<ShipInput, uint> ClientTick { get; }

        public ShipInputCols(string tableName)
        {
            ShipId = new global::SpacetimeDB.Col<ShipInput, ulong>(tableName, "ship_id");
            Thrust = new global::SpacetimeDB.Col<ShipInput, float>(tableName, "thrust");
            StrafeX = new global::SpacetimeDB.Col<ShipInput, float>(tableName, "strafe_x");
            StrafeY = new global::SpacetimeDB.Col<ShipInput, float>(tableName, "strafe_y");
            Yaw = new global::SpacetimeDB.Col<ShipInput, float>(tableName, "yaw");
            Pitch = new global::SpacetimeDB.Col<ShipInput, float>(tableName, "pitch");
            Roll = new global::SpacetimeDB.Col<ShipInput, float>(tableName, "roll");
            Firing = new global::SpacetimeDB.Col<ShipInput, bool>(tableName, "firing");
            ClientTick = new global::SpacetimeDB.Col<ShipInput, uint>(tableName, "client_tick");
        }
    }

    public sealed class ShipInputIxCols
    {
        public global::SpacetimeDB.IxCol<ShipInput, ulong> ShipId { get; }

        public ShipInputIxCols(string tableName)
        {
            ShipId = new global::SpacetimeDB.IxCol<ShipInput, ulong>(tableName, "ship_id");
        }
    }
}
