// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ShipHandle : RemoteTableHandle<EventContext, Ship>
        {
            protected override string RemoteTableName => "ship";

            public sealed class SectorIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(Ship row) => row.SectorId;

                public SectorIdIndex(ShipHandle table) : base(table) { }
            }

            public readonly SectorIdIndex SectorId;

            public sealed class ShipIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Ship row) => row.ShipId;

                public ShipIdUniqueIndex(ShipHandle table) : base(table) { }
            }

            public readonly ShipIdUniqueIndex ShipId;

            internal ShipHandle(DbConnection conn) : base(conn)
            {
                SectorId = new(this);
                ShipId = new(this);
            }

            protected override object GetPrimaryKey(Ship row) => row.ShipId;
        }

        public readonly ShipHandle Ship;
    }

    public sealed class ShipCols
    {
        public global::SpacetimeDB.Col<Ship, ulong> ShipId { get; }
        public global::SpacetimeDB.Col<Ship, SpacetimeDB.Identity> Owner { get; }
        public global::SpacetimeDB.Col<Ship, byte> Team { get; }
        public global::SpacetimeDB.Col<Ship, uint> SectorId { get; }
        public global::SpacetimeDB.Col<Ship, ShipClass> Class { get; }
        public global::SpacetimeDB.Col<Ship, float> PosX { get; }
        public global::SpacetimeDB.Col<Ship, float> PosY { get; }
        public global::SpacetimeDB.Col<Ship, float> PosZ { get; }
        public global::SpacetimeDB.Col<Ship, float> VelX { get; }
        public global::SpacetimeDB.Col<Ship, float> VelY { get; }
        public global::SpacetimeDB.Col<Ship, float> VelZ { get; }
        public global::SpacetimeDB.Col<Ship, float> RotX { get; }
        public global::SpacetimeDB.Col<Ship, float> RotY { get; }
        public global::SpacetimeDB.Col<Ship, float> RotZ { get; }
        public global::SpacetimeDB.Col<Ship, float> RotW { get; }
        public global::SpacetimeDB.Col<Ship, float> AngVelX { get; }
        public global::SpacetimeDB.Col<Ship, float> AngVelY { get; }
        public global::SpacetimeDB.Col<Ship, float> AngVelZ { get; }
        public global::SpacetimeDB.Col<Ship, float> AbPower { get; }
        public global::SpacetimeDB.Col<Ship, float> Health { get; }
        public global::SpacetimeDB.Col<Ship, float> Mass { get; }
        public global::SpacetimeDB.Col<Ship, uint> LastInputTick { get; }
        public global::SpacetimeDB.Col<Ship, uint> LastFireTick { get; }
        public global::SpacetimeDB.Col<Ship, bool> IsPig { get; }
        public global::SpacetimeDB.Col<Ship, bool> IsPod { get; }

        public ShipCols(string tableName)
        {
            ShipId = new global::SpacetimeDB.Col<Ship, ulong>(tableName, "ship_id");
            Owner = new global::SpacetimeDB.Col<Ship, SpacetimeDB.Identity>(tableName, "owner");
            Team = new global::SpacetimeDB.Col<Ship, byte>(tableName, "team");
            SectorId = new global::SpacetimeDB.Col<Ship, uint>(tableName, "sector_id");
            Class = new global::SpacetimeDB.Col<Ship, ShipClass>(tableName, "class");
            PosX = new global::SpacetimeDB.Col<Ship, float>(tableName, "pos_x");
            PosY = new global::SpacetimeDB.Col<Ship, float>(tableName, "pos_y");
            PosZ = new global::SpacetimeDB.Col<Ship, float>(tableName, "pos_z");
            VelX = new global::SpacetimeDB.Col<Ship, float>(tableName, "vel_x");
            VelY = new global::SpacetimeDB.Col<Ship, float>(tableName, "vel_y");
            VelZ = new global::SpacetimeDB.Col<Ship, float>(tableName, "vel_z");
            RotX = new global::SpacetimeDB.Col<Ship, float>(tableName, "rot_x");
            RotY = new global::SpacetimeDB.Col<Ship, float>(tableName, "rot_y");
            RotZ = new global::SpacetimeDB.Col<Ship, float>(tableName, "rot_z");
            RotW = new global::SpacetimeDB.Col<Ship, float>(tableName, "rot_w");
            AngVelX = new global::SpacetimeDB.Col<Ship, float>(tableName, "ang_vel_x");
            AngVelY = new global::SpacetimeDB.Col<Ship, float>(tableName, "ang_vel_y");
            AngVelZ = new global::SpacetimeDB.Col<Ship, float>(tableName, "ang_vel_z");
            AbPower = new global::SpacetimeDB.Col<Ship, float>(tableName, "ab_power");
            Health = new global::SpacetimeDB.Col<Ship, float>(tableName, "health");
            Mass = new global::SpacetimeDB.Col<Ship, float>(tableName, "mass");
            LastInputTick = new global::SpacetimeDB.Col<Ship, uint>(tableName, "last_input_tick");
            LastFireTick = new global::SpacetimeDB.Col<Ship, uint>(tableName, "last_fire_tick");
            IsPig = new global::SpacetimeDB.Col<Ship, bool>(tableName, "is_pig");
            IsPod = new global::SpacetimeDB.Col<Ship, bool>(tableName, "is_pod");
        }
    }

    public sealed class ShipIxCols
    {
        public global::SpacetimeDB.IxCol<Ship, ulong> ShipId { get; }
        public global::SpacetimeDB.IxCol<Ship, uint> SectorId { get; }

        public ShipIxCols(string tableName)
        {
            ShipId = new global::SpacetimeDB.IxCol<Ship, ulong>(tableName, "ship_id");
            SectorId = new global::SpacetimeDB.IxCol<Ship, uint>(tableName, "sector_id");
        }
    }
}
