// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SimEndpointHandle : RemoteTableHandle<EventContext, SimEndpoint>
        {
            protected override string RemoteTableName => "sim_endpoint";

            public sealed class IdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(SimEndpoint row) => row.Id;

                public IdUniqueIndex(SimEndpointHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal SimEndpointHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(SimEndpoint row) => row.Id;
        }

        public readonly SimEndpointHandle SimEndpoint;
    }

    public sealed class SimEndpointCols
    {
        public global::SpacetimeDB.Col<SimEndpoint, byte> Id { get; }
        public global::SpacetimeDB.Col<SimEndpoint, string> Url { get; }

        public SimEndpointCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<SimEndpoint, byte>(tableName, "id");
            Url = new global::SpacetimeDB.Col<SimEndpoint, string>(tableName, "url");
        }
    }

    public sealed class SimEndpointIxCols
    {
        public global::SpacetimeDB.IxCol<SimEndpoint, byte> Id { get; }

        public SimEndpointIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<SimEndpoint, byte>(tableName, "id");
        }
    }
}
