// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SimTickTimerHandle : RemoteTableHandle<EventContext, SimTickTimer>
        {
            protected override string RemoteTableName => "sim_tick_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(SimTickTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(SimTickTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal SimTickTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(SimTickTimer row) => row.ScheduledId;
        }

        public readonly SimTickTimerHandle SimTickTimer;
    }

    public sealed class SimTickTimerCols
    {
        public global::SpacetimeDB.Col<SimTickTimer, ulong> ScheduledId { get; }
        public global::SpacetimeDB.Col<SimTickTimer, SpacetimeDB.ScheduleAt> ScheduledAt { get; }

        public SimTickTimerCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.Col<SimTickTimer, ulong>(tableName, "scheduled_id");
            ScheduledAt = new global::SpacetimeDB.Col<SimTickTimer, SpacetimeDB.ScheduleAt>(tableName, "scheduled_at");
        }
    }

    public sealed class SimTickTimerIxCols
    {
        public global::SpacetimeDB.IxCol<SimTickTimer, ulong> ScheduledId { get; }

        public SimTickTimerIxCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.IxCol<SimTickTimer, ulong>(tableName, "scheduled_id");
        }
    }
}
