// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WeaponDefHandle : RemoteTableHandle<EventContext, WeaponDef>
        {
            protected override string RemoteTableName => "weapon_def";

            public sealed class WeaponIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(WeaponDef row) => row.WeaponId;

                public WeaponIdUniqueIndex(WeaponDefHandle table) : base(table) { }
            }

            public readonly WeaponIdUniqueIndex WeaponId;

            internal WeaponDefHandle(DbConnection conn) : base(conn)
            {
                WeaponId = new(this);
            }

            protected override object GetPrimaryKey(WeaponDef row) => row.WeaponId;
        }

        public readonly WeaponDefHandle WeaponDef;
    }

    public sealed class WeaponDefCols
    {
        public global::SpacetimeDB.Col<WeaponDef, uint> WeaponId { get; }
        public global::SpacetimeDB.Col<WeaponDef, string> Name { get; }
        public global::SpacetimeDB.Col<WeaponDef, float> Damage { get; }
        public global::SpacetimeDB.Col<WeaponDef, uint> FireIntervalTicks { get; }
        public global::SpacetimeDB.Col<WeaponDef, float> ProjectileSpeed { get; }
        public global::SpacetimeDB.Col<WeaponDef, uint> ProjectileLifeTicks { get; }
        public global::SpacetimeDB.Col<WeaponDef, float> ProjectileRadius { get; }
        public global::SpacetimeDB.Col<WeaponDef, float> SpreadRad { get; }

        public WeaponDefCols(string tableName)
        {
            WeaponId = new global::SpacetimeDB.Col<WeaponDef, uint>(tableName, "weapon_id");
            Name = new global::SpacetimeDB.Col<WeaponDef, string>(tableName, "name");
            Damage = new global::SpacetimeDB.Col<WeaponDef, float>(tableName, "damage");
            FireIntervalTicks = new global::SpacetimeDB.Col<WeaponDef, uint>(tableName, "fire_interval_ticks");
            ProjectileSpeed = new global::SpacetimeDB.Col<WeaponDef, float>(tableName, "projectile_speed");
            ProjectileLifeTicks = new global::SpacetimeDB.Col<WeaponDef, uint>(tableName, "projectile_life_ticks");
            ProjectileRadius = new global::SpacetimeDB.Col<WeaponDef, float>(tableName, "projectile_radius");
            SpreadRad = new global::SpacetimeDB.Col<WeaponDef, float>(tableName, "spread_rad");
        }
    }

    public sealed class WeaponDefIxCols
    {
        public global::SpacetimeDB.IxCol<WeaponDef, uint> WeaponId { get; }

        public WeaponDefIxCols(string tableName)
        {
            WeaponId = new global::SpacetimeDB.IxCol<WeaponDef, uint>(tableName, "weapon_id");
        }
    }
}
