// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WorldConfigHandle : RemoteTableHandle<EventContext, WorldConfig>
        {
            protected override string RemoteTableName => "world_config";

            public sealed class IdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(WorldConfig row) => row.Id;

                public IdUniqueIndex(WorldConfigHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal WorldConfigHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(WorldConfig row) => row.Id;
        }

        public readonly WorldConfigHandle WorldConfig;
    }

    public sealed class WorldConfigCols
    {
        public global::SpacetimeDB.Col<WorldConfig, byte> Id { get; }
        public global::SpacetimeDB.Col<WorldConfig, float> SectorScale { get; }
        public global::SpacetimeDB.Col<WorldConfig, float> AsteroidDensity { get; }

        public WorldConfigCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<WorldConfig, byte>(tableName, "id");
            SectorScale = new global::SpacetimeDB.Col<WorldConfig, float>(tableName, "sector_scale");
            AsteroidDensity = new global::SpacetimeDB.Col<WorldConfig, float>(tableName, "asteroid_density");
        }
    }

    public sealed class WorldConfigIxCols
    {
        public global::SpacetimeDB.IxCol<WorldConfig, byte> Id { get; }

        public WorldConfigIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<WorldConfig, byte>(tableName, "id");
        }
    }
}
