// Wire-format codec tests (tests/WireTest). Console PASS/FAIL in the repo's test idiom; exits
// non-zero on any failure.
//
// The generated codecs (tools/wire-gen over shared/Net/Messages.cs + Records.cs) are the ONLY
// definition of the wire format; the server fills them (server/Net/Frames.cs) and the Godot client
// reads them. The legacy hand-written writers were proven byte-identical before they were deleted
// (this suite's history); the goldens in section 8 pin those layouts. Sections:
//
//   1. every fixed record/frame Size and message id matches its literal pin
//   2. entity records + one-shot frames: fill from synthetic sim state, parse back, check every field
//   3. world/content-backed frames on the stock bundle: Welcome (fog off/on), Reveal, Defs, MapList,
//      TeamState, Research, Contacts, Bases, RockUpdates, Loadouts, ConstructorState, Lobby, Stats
//   4. Hello: every field optional — shorter (older) frames and torn tails parse with the rest ""
//   5. client->server frames: the Godot client's hand-packed layouts (replicated here byte for byte)
//      == generated ToBytes(); Spawn's optional tails parse exactly as ClientHub does today
//   6. write -> read -> write round-trips for synthetic instances of every frame (nullable blocks,
//      7-bit strings past 127 bytes, [WireIgnore] fields dropped, u16/u32 counts)
//   7. hostile input: truncation at every prefix length never throws and never parses; count bombs
//      fail without allocating; a wrong id fails
//   8. durable goldens: hex / SHA-256 of synthetic frames pinned so a layout drift is caught
//      (`--print-goldens` regenerates the table after an INTENDED change + a Wire.ProtocolVersion bump)
//
// Run: dotnet run --project tests/WireTest -c Release
using System.Security.Cryptography;
using System.Text;
using SimServer.Content;
using SimServer.Net;
using SimServer.Sim;
using StellarAllegiance.Shared;
using StellarAllegiance.Shared.Net;

int failures = 0;
bool printGoldens = args.Contains("--print-goldens");
var computedGoldens = new List<(string Name, string Value)>();

void Check(bool ok, string pass, string fail)
{
    if (ok)
        Console.WriteLine($"PASS  {pass}");
    else
    {
        Console.WriteLine($"FAIL  {fail}");
        failures++;
    }
}

static string Hex(ReadOnlySpan<byte> b) => Convert.ToHexString(b);

static string Sha(byte[] b) => Convert.ToHexString(SHA256.HashData(b));

static string Diff(byte[] a, byte[] b)
{
    if (a.Length != b.Length)
        return $"length {a.Length} vs {b.Length}";
    for (int i = 0; i < a.Length; i++)
        if (a[i] != b[i])
            return $"first difference at byte {i}: {a[i]:X2} vs {b[i]:X2}";
    return "identical";
}

// Reference bytes (a layout replicated verbatim from the Godot client's hand-packed senders) vs the
// generated codec's output.
void Same(string what, byte[] reference, byte[] generated) =>
    Check(
        reference.AsSpan().SequenceEqual(generated),
        $"{what}: generated bytes == reference bytes ({reference.Length} B)",
        $"{what}: {Diff(reference, generated)}"
    );

void Golden(string name, byte[] bytes, bool hash = true)
{
    string value = hash ? Sha(bytes) : Hex(bytes);
    computedGoldens.Add((name, value));
    if (printGoldens)
        return;
    if (!Goldens.Table.TryGetValue(name, out var expected))
    {
        Check(false, "", $"golden '{name}' missing from the table (run with --print-goldens and paste)");
        return;
    }
    Check(
        expected == value,
        $"golden {name} unchanged",
        $"golden {name} CHANGED: expected {expected} got {value} — a wire layout moved; bump Wire.ProtocolVersion and re-pin"
    );
}

string stockPath = Path.Combine(AppContext.BaseDirectory, "content", "core", "core.manifest.yaml");
string worldPath = Path.Combine(AppContext.BaseDirectory, "content", "core", "world.yaml");
string mapsDir = Path.Combine(AppContext.BaseDirectory, "content", "maps");

// ================================================================================================
// 1. Sizes + ids (literal pins — these ARE the protocol; a change here is a Wire.ProtocolVersion bump)
// ================================================================================================
Console.WriteLine("---- 1. fixed sizes + message ids ----");
var sizePins = new (string, int, int)[]
{
    ("ShipRecord", ShipRecord.Size, 57),
    ("MissileRecord", MissileRecord.Size, 35),
    ("MinefieldRecord", MinefieldRecord.Size, 41),
    ("ContactRecord", ContactRecord.Size, 28),
    ("ProbeRecord", ProbeRecord.Size, 29),
    ("SalvageRecord", SalvageRecord.Size, 29),
    ("RockUpdateRecord", RockUpdateRecord.Size, 13),
    ("MinerTargetRecord", MinerTargetRecord.Size, 16),
    ("ConstructorBuildRecord", ConstructorBuildRecord.Size, 19),
    ("BaseHealthRecord", BaseHealthRecord.Size, 12),
    ("ConstructorStateRecord", ConstructorStateRecord.Size, 43),
    ("HoldItemRecord", HoldItemRecord.Size, 6),
    ("BaseStatic", BaseStatic.Size, 34),
    ("RockStatic", RockStatic.Size, 51),
    ("AlephStatic", AlephStatic.Size, 28),
    ("DustCloudWire", DustCloudWire.Size, 20),
    ("SunEnvWire", SunEnvWire.Size, 40),
    ("HardpointDef", HardpointDef.Size, 31),
    ("CargoLoadDef", CargoLoadDef.Size, 5),
    ("AttrMod", AttrMod.Size, 5),
    ("WorldConfigWire", WorldConfigWire.Size, 12),
    ("InputMessage", InputMessage.Size, 38),
    ("SetAutopilotMessage", SetAutopilotMessage.Size, 27),
    ("OrderMessage", OrderMessage.Size, 34),
    ("ResearchMessage", ResearchMessage.Size, 12),
    ("BuildConstructorMessage", BuildConstructorMessage.Size, 10),
    ("ConstructorCancelMessage", ConstructorCancelMessage.Size, 9),
    ("BuyMinerMessage", BuyMinerMessage.Size, 9),
    ("MissileGoneMessage", MissileGoneMessage.Size, 18),
    ("ProbeGoneMessage", ProbeGoneMessage.Size, 18),
    ("MineGoneMessage", MineGoneMessage.Size, 19),
    ("ChaffMessage", ChaffMessage.Size, 28),
    ("SalvageGoneMessage", SalvageGoneMessage.Size, 26),
    ("YouAreMessage", YouAreMessage.Size, 9),
    ("ShipGoneMessage", ShipGoneMessage.Size, 10),
    ("PongMessage", PongMessage.Size, 5),
    ("PingMessage", PingMessage.Size, 5),
    ("RejectMessage", RejectMessage.Size, 2),
    ("SetTeamMessage", SetTeamMessage.Size, 2),
    ("SetReadyMessage", SetReadyMessage.Size, 2),
    ("ByeMessage", ByeMessage.Size, 1),
};
bool sizesOk = true;
foreach (var (n, actual, expected) in sizePins)
    if (actual != expected)
    {
        sizesOk = false;
        Console.WriteLine($"      size mismatch {n}: {actual} (expected {expected})");
    }
Check(sizesOk, $"all {sizePins.Length} fixed sizes match their pins", "fixed size mismatch (see above)");
Check(SnapshotMessage.HeaderSize == 9, "SnapshotMessage.HeaderSize == 9", "snapshot header");

var idPairs = new (string, byte, byte)[]
{
    ("Hello", HelloMessage.MsgId, 1),
    ("Input", InputMessage.MsgId, 2),
    ("Ping", PingMessage.MsgId, 3),
    ("Spawn", SpawnMessage.MsgId, 4),
    ("SetTeam", SetTeamMessage.MsgId, 5),
    ("SetReady", SetReadyMessage.MsgId, 6),
    ("Chat", ChatMessage.MsgId, 7),
    ("Bye", ByeMessage.MsgId, 8),
    ("SetTeamName", SetTeamNameMessage.MsgId, 9),
    ("SetMap", SetMapMessage.MsgId, 10),
    ("SetAutopilot", SetAutopilotMessage.MsgId, 11),
    ("Order", OrderMessage.MsgId, 12),
    ("Research", ResearchMessage.MsgId, 13),
    ("BuildConstructor", BuildConstructorMessage.MsgId, 14),
    ("ConstructorCancel", ConstructorCancelMessage.MsgId, 15),
    ("BuyMiner", BuyMinerMessage.MsgId, 16),
    ("Welcome", WelcomeMessage.MsgId, 1),
    ("YouAre", YouAreMessage.MsgId, 2),
    ("Snapshot", SnapshotMessage.MsgId, 3),
    ("ShipGone", ShipGoneMessage.MsgId, 4),
    ("Bases", BasesMessage.MsgId, 5),
    ("Pong", PongMessage.MsgId, 6),
    ("Defs", DefsMessage.MsgId, 7),
    ("LobbyState", LobbyStateMessage.MsgId, 8),
    ("ChatRelay", ChatRelayMessage.MsgId, 9),
    ("TeamState", TeamStateMessage.MsgId, 10),
    ("Missiles", MissilesMessage.MsgId, 11),
    ("MissileGone", MissileGoneMessage.MsgId, 12),
    ("Minefields", MinefieldsMessage.MsgId, 13),
    ("MineGone", MineGoneMessage.MsgId, 14),
    ("Chaff", ChaffMessage.MsgId, 15),
    ("Reveal", RevealMessage.MsgId, 16),
    ("Contacts", ContactsMessage.MsgId, 17),
    ("Probes", ProbesMessage.MsgId, 18),
    ("ProbeGone", ProbeGoneMessage.MsgId, 19),
    ("MapList", MapListMessage.MsgId, 20),
    ("Reject", RejectMessage.MsgId, 21),
    ("RockUpdate", RockUpdateMessage.MsgId, 22),
    ("MinerTargets", MinerTargetsMessage.MsgId, 23),
    ("ResearchState", ResearchStateMessage.MsgId, 24),
    ("ConstructorBuilds", ConstructorBuildsMessage.MsgId, 25),
    ("ConstructorState", ConstructorStateMessage.MsgId, 26),
    ("RockGone", RockGoneMessage.MsgId, 27),
    ("ShipLoadout", ShipLoadoutMessage.MsgId, 28),
    ("MatchStats", MatchStatsMessage.MsgId, 29),
    ("Salvage", SalvageMessage.MsgId, 30),
    ("SalvageGone", SalvageGoneMessage.MsgId, 31),
};
bool idsOk = true;
foreach (var (n, a, b) in idPairs)
    if (a != b)
    {
        idsOk = false;
        Console.WriteLine($"      id mismatch {n}: {a} (expected {b})");
    }
Check(idsOk, $"all {idPairs.Length} message ids match their pins", "message id mismatch (see above)");
Check(
    ShipFlags.Pig == 1
        && ShipFlags.Pod == 2
        && ShipFlags.LockingMe == 4
        && ShipFlags.LockedMe == 8
        && ShipFlags.Autopilot == 16
        && ShipFlags.Miner == 32
        && ShipFlags.Mining == 64
        && ShipFlags.Constructor == 128,
    "ShipFlags bits pinned",
    "ship flag bits moved"
);
Check(
    InputFlags.Firing == 1
        && InputFlags.Boost == 2
        && InputFlags.Firing2 == 4
        && InputFlags.DropChaff == 8
        && InputFlags.DropMine == 16
        && InputFlags.DropProbe == 32,
    "InputFlags bits pinned",
    "input flag bits moved"
);
Check(
    Protocol.ShipRecordSize == ShipRecord.Size
        && Protocol.MsgSnapshot == SnapshotMessage.MsgId
        && Protocol.ShipFlagMining == ShipFlags.Mining
        && Protocol.FlagBoost == InputFlags.Boost,
    "the server Protocol facade aliases the shared constants",
    "Protocol facade drift"
);

// ================================================================================================
// 2. Entity records + one-shot frames: fill from synthetic sim state, parse back, check every field
// ================================================================================================
Console.WriteLine("---- 2. records: fill → bytes → parse ----");
static bool Near(float a, float b, float tol) => MathF.Abs(a - b) <= tol;

static bool NearV(Vec3 a, Vec3 b, float tol) => Near(a.X, b.X, tol) && Near(a.Y, b.Y, tol) && Near(a.Z, b.Z, tol);

// f16 keeps ~3 significant digits: tolerance relative to magnitude, floored for tiny values.
static bool NearHalf(float a, float b) => Near(a, b, MathF.Max(MathF.Abs(b) * 2e-3f, 1e-3f));

static bool NearHalfV(Vec3 a, Vec3 b) => NearHalf(a.X, b.X) && NearHalf(a.Y, b.Y) && NearHalf(a.Z, b.Z);

Simulation.ShipSim MakeShip(
    ulong id,
    byte team,
    byte cls,
    ShipKind kind,
    bool pig,
    byte threat,
    bool ap,
    bool harvesting,
    Vec3 pos
) =>
    new()
    {
        ShipId = id,
        Team = team,
        Class = cls,
        Kind = kind,
        IsPig = pig,
        ThreatLockState = threat,
        ApEngaged = ap,
        IsHarvesting = harvesting,
        SectorId = 7,
        State = new ShipState
        {
            Pos = pos,
            Vel = new Vec3(12.5f, -3.25f, 0.001f),
            Rot = new Quat(0.1f, -0.2f, 0.3f, 0.9f).Normalized(),
            AngVel = new Vec3(-0.5f, 1.25f, 2f),
            AbPower = 0.75f,
            Fuel = 33.3f,
            Mass = 100f,
        },
        Health = 87.5f,
        Shield = 12.25f,
        LastInputTick = 123456,
        LastFireTick = 123400,
        MissileAmmo = 6,
        LockState = 0x80 | 42,
        ChaffAmmo = 3,
        MineAmmo = 2,
        ProbeAmmo = 1,
        FuelPodAmmo = 4,
        Alive = true,
    };

var ships = new[]
{
    MakeShip(0x1122334455667788UL, 0, 1, ShipKind.Combat, false, 0, false, false, new Vec3(100f, -250f, 3000f)),
    MakeShip(2, 1, 255, ShipKind.Pod, true, 2, false, false, new Vec3(-9000f, 8191.9f, 0f)), // pos clamps at ±8192
    MakeShip(3, 0, 5, ShipKind.Miner, false, 1, true, true, new Vec3(0.13f, 0.12f, -0.13f)),
    MakeShip(4, 1, 6, ShipKind.Constructor, false, 0, true, false, new Vec3(4725f, 4725f, 4725f)),
};
foreach (var s in ships)
{
    var rec = Frames.ShipRecordOf(s);
    var buf = new byte[ShipRecord.Size];
    int wrote = rec.Write(buf);
    Check(wrote == ShipRecord.Size, "ShipRecord.Write returns Size", $"wrote {wrote}");
    var back = ShipRecord.Parse(buf);
    var clampedPos = new Vec3(
        Math.Clamp(s.State.Pos.X, -WireQuant.PosRange, WireQuant.PosRange),
        Math.Clamp(s.State.Pos.Y, -WireQuant.PosRange, WireQuant.PosRange),
        Math.Clamp(s.State.Pos.Z, -WireQuant.PosRange, WireQuant.PosRange)
    );
    float rotDot =
        back.Rot.X * s.State.Rot.X + back.Rot.Y * s.State.Rot.Y + back.Rot.Z * s.State.Rot.Z + back.Rot.W * s.State.Rot.W;
    Check(
        back.ShipId == s.ShipId
            && back.Team == s.Team
            && back.Class == s.Class
            && back.Sector == s.SectorId
            && back.Kind == s.Kind
            && back.IsPig == s.IsPig
            && back.ThreatLock == s.ThreatLockState
            && back.Autopilot == s.ApEngaged
            && back.IsMining == s.IsHarvesting
            && NearV(back.Pos, clampedPos, 0.126f)
            && MathF.Abs(rotDot) > 0.9999f
            && NearHalfV(back.Vel, s.State.Vel)
            && NearHalfV(back.AngVel, s.State.AngVel)
            && NearHalf(back.AbPower, s.State.AbPower)
            && NearHalf(back.Fuel, s.State.Fuel)
            && NearHalf(back.Health, s.Health)
            && NearHalf(back.Shield, s.Shield)
            && back.LastInputTick == s.LastInputTick
            && back.LastFireTick == s.LastFireTick
            && back.MissileAmmo == s.MissileAmmo
            && back.LockState == s.LockState
            && back.ChaffAmmo == s.ChaffAmmo
            && back.MineAmmo == s.MineAmmo
            && back.ProbeAmmo == s.ProbeAmmo
            && back.FuelPodAmmo == s.FuelPodAmmo,
        $"ShipRecord ship {s.ShipId} ({s.Kind}, pig={s.IsPig}, threat={s.ThreatLockState}, ap={s.ApEngaged}) fills + parses (pos within 0.125 u, rot within 0.003 rad, f16 rates)",
        $"ShipRecord ship {s.ShipId}: a field did not survive the fill/parse"
    );
}

var missile = new Simulation.MissileSim
{
    MissileId = 0xA1B2C3D4E5F60718UL,
    WeaponId = 3,
    Team = 1,
    SectorId = 12,
    Pos = new Vec3(-1200.5f, 33f, 999.25f),
    Vel = new Vec3(300f, -20f, 5.5f),
    TargetShipId = 0x99,
};
{
    var back = MissileRecord.Parse(Frames.MissileRecordOf(missile).ToBytes());
    Check(
        back.MissileId == missile.MissileId
            && back.WeaponId == 3
            && back.Team == 1
            && back.Sector == 12
            && back.TargetShipId == 0x99
            && NearV(back.Pos, missile.Pos, 0.126f)
            && NearHalfV(back.Vel, missile.Vel),
        "MissileRecord fills + parses",
        "MissileRecord fields"
    );
}
var field = new Simulation.MineFieldSim
{
    FieldId = 77,
    WeaponId = 7,
    Team = 0,
    SectorId = 3,
    Center = new Vec3(10f, 20f, -30f),
    Seed = 0xDEADBEEF,
    ArmAtTick = 500,
    ExpireAtTick = 9000,
    AliveMask = 0xFFFF_0000_FFFF_00FFUL,
};
{
    var back = MinefieldRecord.Parse(Frames.MinefieldRecordOf(field).ToBytes());
    Check(
        back.FieldId == 77
            && back.WeaponId == 7
            && back.Team == 0
            && back.Sector == 3
            && NearV(back.Center, field.Center, 0.126f)
            && back.Seed == 0xDEADBEEF
            && back.ArmAtTick == 500
            && back.ExpireAtTick == 9000
            && back.AliveMask == field.AliveMask,
        "MinefieldRecord fills + parses (seed + alive mask exact)",
        "MinefieldRecord fields"
    );
}
var probe = new Simulation.ProbeSim
{
    ProbeId = 501,
    Team = 1,
    WeaponId = 8,
    SectorId = 2,
    Pos = new Vec3(1.5f, -2.5f, 3.5f),
    ExpireAtTick = 100_000,
};
foreach (var (tick, left) in new (uint, ushort)[] { (0, 65535), (99_000, 1000), (100_001, 0) })
{
    var back = ProbeRecord.Parse(Frames.ProbeRecordOf(probe, tick).ToBytes());
    Check(
        back.ProbeId == 501
            && back.Team == 1
            && back.WeaponId == 8
            && back.Sector == 2
            && back.Pos.X == 1.5f
            && back.Pos.Y == -2.5f
            && back.Pos.Z == 3.5f
            && back.TicksLeft == left,
        $"ProbeRecord at tick {tick}: full-precision pos, ticksLeft {left} (saturating)",
        $"ProbeRecord tick {tick}: ticksLeft {back.TicksLeft}"
    );
}
var item = new Simulation.SalvageSim
{
    Id = 0xFEEDFACECAFEBEEFUL,
    SectorId = 5,
    Pos = new Vec3(-300f, 0.25f, 12f),
    Vel = new Vec3(-4f, 2f, 0.5f),
    Kind = 2,
    ItemId = 4,
    Count = 6,
    Team = 1,
    ExpireAtTick = 4000,
};
{
    var back = SalvageRecord.Parse(Frames.SalvageRecordOf(item, 940).ToBytes());
    Check(
        back.Id == item.Id
            && back.Kind == 2
            && back.ItemId == 4
            && back.Count == 6
            && back.Team == 1
            && NearV(back.Pos, item.Pos, 0.126f)
            && NearHalfV(back.Vel, item.Vel)
            && back.TicksLeft == 3060,
        "SalvageRecord fills + parses (ticksLeft = expire - tick)",
        "SalvageRecord fields"
    );
}
var chaff = new Simulation.ChaffSim
{
    ChaffId = 31337,
    Team = 0,
    WeaponId = 6,
    SectorId = 9,
    Pos = new Vec3(5f, 6f, 7f),
    Vel = new Vec3(-1f, -2f, -3f),
    ExpireAtTick = 10,
};
{
    var back = ChaffMessage.Parse(Frames.ChaffOf(chaff).ToBytes());
    Check(
        back.Id == 31337
            && back.Team == 0
            && back.Sector == 9
            && back.WeaponId == 6
            && NearV(back.Pos, chaff.Pos, 0.126f)
            && NearHalfV(back.Vel, chaff.Vel),
        "Chaff fills + parses",
        "Chaff fields"
    );
}
var gonePos = new Vec3(123.4f, -56.7f, 8.9f);
{
    var mg = MissileGoneMessage.Parse(Protocol.BuildMissileGone(0x1234, 1, 4, gonePos));
    var mn = MineGoneMessage.Parse(Protocol.BuildMineGone(77, 13, 2, 3, gonePos));
    var pg = ProbeGoneMessage.Parse(Protocol.BuildProbeGone(501, 2, 2, gonePos));
    var sg = SalvageGoneMessage.Parse(Protocol.BuildSalvageGone(item.Id, 2, 5, gonePos, 0xABCDEF0123UL));
    Check(
        mg.Id == 0x1234 && mg.Reason == 1 && mg.Sector == 4 && NearV(mg.Pos, gonePos, 0.126f),
        "MissileGone builds + parses",
        "MissileGone"
    );
    Check(
        mn.FieldId == 77 && mn.MineIndex == 13 && mn.Reason == 2 && mn.Sector == 3 && NearV(mn.Pos, gonePos, 0.126f),
        "MineGone builds + parses",
        "MineGone"
    );
    Check(pg.Id == 501 && pg.Reason == 2 && pg.Sector == 2, "ProbeGone builds + parses", "ProbeGone");
    Check(
        sg.Id == item.Id
            && sg.Reason == 2
            && sg.Sector == 5
            && sg.ByShipId == 0xABCDEF0123UL
            && NearV(sg.Pos, gonePos, 0.126f),
        "SalvageGone builds + parses (collector id)",
        "SalvageGone"
    );
    Check(
        YouAreMessage.Parse(Protocol.BuildYouAre(0x0102030405060708UL)).ShipId == 0x0102030405060708UL,
        "YouAre builds + parses",
        "YouAre"
    );
    var sgone = ShipGoneMessage.Parse(Protocol.BuildShipGone(42, 2));
    Check(sgone.ShipId == 42 && sgone.Reason == 2, "ShipGone builds + parses", "ShipGone");
    Check(PongMessage.Parse(Protocol.BuildPong(0xCAFEBABE)).Nonce == 0xCAFEBABE, "Pong builds + parses", "Pong");
    var cr = ChatRelayMessage.Parse(Protocol.BuildChatRelay(2, 1, "Cmdr Zoë", "attack the ✈ base"));
    Check(
        cr.Scope == 2 && cr.FromTeam == 1 && cr.Name == "Cmdr Zoë" && cr.Text == "attack the ✈ base",
        "ChatRelay builds + parses (UTF-8)",
        "ChatRelay"
    );
    var rg = RockGoneMessage.Parse(Protocol.BuildRockGone(new[] { 5UL, 6UL, 7UL })!);
    Check(rg.RockIds.SequenceEqual(new ulong[] { 5, 6, 7 }), "RockGone builds + parses", "RockGone");
    Check(Protocol.BuildRockGone(Array.Empty<ulong>()) is null, "RockGone: empty → no frame", "RockGone empty");
}

// ================================================================================================
// 3. World / content-backed frames on the stock bundle: fill from real sim state, parse, verify
// ================================================================================================
Console.WriteLine("---- 3. world/content-backed frames ----");
var content = ContentLoader.Load(stockPath, worldPath);
var sim = new Simulation(
    new World(7, content.World, content.Bases[0].MaxHealth, content.Start, content.Ships),
    content,
    rngSeed: 1
);
sim.StartMatch();
var world = sim.World;
Console.WriteLine(
    $"      world: {world.Sectors.Count} sectors, {world.Bases.Count} bases, {world.Asteroids.Count} rocks, {world.Alephs.Count} alephs, {world.DustClouds.Count} dust clouds"
);

var token = new byte[16];
for (int i = 0; i < 16; i++)
    token[i] = (byte)(i * 17);
{
    var w = WelcomeMessage.Parse(Protocol.BuildWelcome(3, 1, world, 4242, token, fog: false));
    Check(
        w.Version == Wire.ProtocolVersion
            && w.ClientId == 3
            && w.Team == 1
            && w.Tick == 4242
            && w.Dt == FlightModel.Dt
            && w.ReconnectToken.AsSpan().SequenceEqual(token)
            && w.Sectors.Length == world.Sectors.Count
            && w.Bases.Length == world.Bases.Count
            && w.Rocks.Length == world.Asteroids.Count
            && w.Alephs.Length == world.Alephs.Count,
        "Welcome (fog off): the full world + identity + token",
        "Welcome fog-off fields"
    );
    Check(
        w.Sectors[0].Name == world.Sectors[0].Name
            && w.Sectors[0].Id == world.Sectors[0].Id
            && w.Sectors[0].Radius == world.Sectors[0].Radius,
        "Welcome: 7-bit sector name + id/radius round-trip",
        $"sector 0 '{w.Sectors[0].Name}'"
    );
    Check(
        w.Bases[0].Id == world.Bases[0].Id
            && w.Bases[0].Health == world.BaseHealth[0]
            && w.Bases[0].Radius == world.BaseRadiusOf(world.Bases[0].BaseTypeId),
        "Welcome: base static carries live health + per-type radius",
        "base static"
    );
    var a0 = world.Asteroids[0];
    Check(
        w.Rocks[0].Id == a0.Id
            && w.Rocks[0].Variant == a0.Variant
            && w.Rocks[0].Radius == a0.Radius
            && w.Rocks[0].CurrentRadius == world.RockCurrentRadius(a0.Id)
            && w.Rocks[0].RockClass == (byte)world.RockClassOf(a0.Id),
        "Welcome: rock static carries class + current radius",
        "rock static"
    );
    int withEnv = w.Sectors.Count(s => s.Env.Any);
    Console.WriteLine($"      {withEnv}/{w.Sectors.Length} sectors carry an environment block");
}
{
    var w = WelcomeMessage.Parse(Protocol.BuildWelcome(3, Wire.NoTeam, world, 4242, token, fog: true, null));
    Check(
        w.Sectors.Length == 0 && w.Bases.Length == 0 && w.Rocks.Length == 0 && w.Alephs.Length == 0 && w.Team == Wire.NoTeam,
        "Welcome (fog on, NoTeam): no statics leak",
        "NoTeam Welcome leaked statics"
    );
}
var vision = new Simulation.TeamVision();
vision.DiscoveredSectors.Add(world.Sectors[0].Id);
if (world.Sectors.Count > 2)
    vision.DiscoveredSectors.Add(world.Sectors[2].Id);
for (int i = 0; i < world.Bases.Count; i += 2)
    vision.DiscoveredBases.Add(world.Bases[i].Id);
vision.LastKnownBaseHealth[world.Bases[0].Id] = 123.5f;
for (int i = 0; i < world.Asteroids.Count; i += 3)
    vision.DiscoveredRocks.Add(world.Asteroids[i].Id);
for (int i = 0; i < world.Alephs.Count; i += 2)
    vision.DiscoveredAlephs.Add(world.Alephs[i].Id);
{
    var w = WelcomeMessage.Parse(Protocol.BuildWelcome(3, 0, world, 4242, token, fog: true, vision));
    Check(
        w.Sectors.Length == vision.DiscoveredSectors.Count
            && w.Bases.Length == vision.DiscoveredBases.Count
            && w.Rocks.Length == vision.DiscoveredRocks.Count
            && w.Alephs.Length == vision.DiscoveredAlephs.Count,
        "Welcome (fog on): only the team's discovered statics",
        "fog Welcome counts"
    );
    Check(
        w.Bases[0].Id == world.Bases[0].Id && w.Bases[0].Health == 123.5f,
        "Welcome (fog on): remembered base health, not live",
        $"base health {w.Bases[0].Health}"
    );
}

// Reveal slice: seed every log, cap the rock slice at RevealMaxRocks per pass, walk the cursors.
vision.RevealLogBases.AddRange(world.Bases.Select(b => b.Id));
vision.RevealLogRocks.AddRange(world.Asteroids.Select(a => a.Id));
vision.RevealLogRocks.Add(0xFFFF_FFFF_FFFF_0000UL); // unresolvable id: skipped, never wedges the cursor
vision.RevealLogAlephs.AddRange(world.Alephs.Select(g => g.Id));
vision.RevealLogSectors.AddRange(world.Sectors.Select(s => s.Id));
var rockIndex = new Dictionary<ulong, int>();
for (int i = 0; i < world.Asteroids.Count; i++)
    rockIndex[world.Asteroids[i].Id] = i;
{
    int bc = 0,
        rc = 0,
        ac = 0,
        sc = 0;
    int pass = 0,
        rocksSeen = 0,
        basesSeen = 0,
        sectorsSeen = 0,
        firstPassRocks = -1;
    while (true)
    {
        var bytes = Protocol.BuildRevealSlice(
            world,
            vision,
            rockIndex,
            bc,
            rc,
            ac,
            sc,
            out int nb,
            out int nr,
            out int na,
            out int ns
        );
        if (bytes is null)
        {
            Check(
                rc == vision.RevealLogRocks.Count && bc == vision.RevealLogBases.Count,
                $"RevealSlice: caught up after {pass} passes",
                "RevealSlice cursors not at the log ends"
            );
            break;
        }
        var r = RevealMessage.Parse(bytes);
        if (pass == 0)
            firstPassRocks = r.Rocks.Length;
        rocksSeen += r.Rocks.Length;
        basesSeen += r.Bases.Length;
        sectorsSeen += r.Sectors.Length;
        Check(
            nr - rc <= Protocol.RevealMaxRocks && nb - bc <= Protocol.RevealMaxBases && ns - sc <= Protocol.RevealMaxSectors,
            $"RevealSlice pass {pass}: slice within caps ({r.Bases.Length} bases, {r.Rocks.Length} rocks, {r.Sectors.Length} sectors)",
            "RevealSlice cap exceeded"
        );
        bc = nb;
        rc = nr;
        ac = na;
        sc = ns;
        if (++pass > 50)
        {
            Check(false, "", "RevealSlice never caught up");
            break;
        }
    }
    Check(
        rocksSeen == world.Asteroids.Count && basesSeen == world.Bases.Count && sectorsSeen == world.Sectors.Count,
        "RevealSlice: every static streamed exactly once; the bogus id was skipped",
        $"rocks {rocksSeen}/{world.Asteroids.Count} bases {basesSeen}"
    );
    Check(
        firstPassRocks == Math.Min(world.Asteroids.Count, Protocol.RevealMaxRocks),
        "RevealSlice: first pass carries min(total, RevealMaxRocks) rocks",
        $"first pass {firstPassRocks}"
    );
    var br = RevealMessage.Parse(Protocol.BuildBaseReveal(world, new[] { world.Bases[0].Id })!);
    Check(
        br.Bases.Length == 1
            && br.Bases[0].Id == world.Bases[0].Id
            && br.Rocks.Length == 0
            && br.Alephs.Length == 0
            && br.Sectors.Length == 0,
        "BaseReveal: one base, nothing else",
        "BaseReveal"
    );
}
{
    var all = BasesMessage.Parse(Protocol.BuildBases(world));
    var some = BasesMessage.Parse(Protocol.BuildBasesFor(world, vision));
    var none = BasesMessage.Parse(Protocol.BuildBasesFor(world, null));
    Check(
        all.Bases.Length == world.Bases.Count && all.Bases[0].Health == world.BaseHealth[0],
        "Bases: every base, live health",
        "Bases"
    );
    Check(
        some.Bases.Length == vision.DiscoveredBases.Count && some.Bases[0].Health == 123.5f,
        "BasesFor (fog): discovered bases with remembered health",
        "BasesFor"
    );
    Check(none.Bases.Length == 0, "BasesFor (null vision): empty", "BasesFor null");
}
{
    var changed = world.Asteroids.Take(300).Select(a => a.Id).ToList();
    var frames = Protocol.BuildRockUpdates(world, changed);
    Check(
        frames.Count == 2
            && RockUpdateMessage.Parse(frames[0]).Rocks.Length == 255
            && RockUpdateMessage.Parse(frames[1]).Rocks.Length == 45,
        "RockUpdates: 300 ids chunk into 255 + 45",
        $"chunks {frames.Count}"
    );
    var r0 = RockUpdateMessage.Parse(frames[0]).Rocks[0];
    Check(
        r0.RockId == changed[0]
            && r0.CurrentRadius == world.RockCurrentRadius(changed[0])
            && r0.OrePct == Frames.RockOrePct(world, changed[0]),
        "RockUpdates: record carries current radius + ore pct",
        "RockUpdates record"
    );
    int discovered = changed.Count(id => vision.DiscoveredRocks.Contains(id));
    var forTeam = Protocol.BuildRockUpdatesFor(world, vision, changed);
    Check(
        forTeam.Sum(f => RockUpdateMessage.Parse(f).Rocks.Length) == discovered,
        $"RockUpdatesFor: only the {discovered} discovered rocks",
        "RockUpdatesFor filter"
    );
    Check(
        Protocol.BuildRockUpdatesFor(world, null, changed).Count == 0,
        "RockUpdatesFor: null vision → no frames",
        "RockUpdatesFor null vision"
    );
}
{
    var ts = TeamStateMessage.Parse(Protocol.BuildTeamState(sim));
    Check(ts.Teams.Length == world.TeamStates.Count, "TeamState: one row per team", $"rows {ts.Teams.Length}");
    var t0 = ts.Teams.First(t => t.Team == 0);
    var st0 = world.TeamStates[0];
    Check(
        t0.Credits == st0.Credits
            && t0.Score == st0.Score
            && t0.UnlockedClasses.Length == st0.UnlockedClasses.Count
            && t0.OwnedCaps.Length == st0.OwnedCapabilities.Count
            && t0.MinerCap == (byte)world.Mining.MaxMinersPerTeam
            && t0.BuildQueueLimit == (byte)world.Build.QueueLimit
            && t0.MinerCount == (byte)sim.MinerCount(0),
        "TeamState: credits/score/unlocks/caps/miner + queue knobs",
        "TeamState row 0"
    );
    Check(
        t0.UnlockedClasses.SequenceEqual(t0.UnlockedClasses.OrderBy(x => x))
            && t0.OwnedTechs.SequenceEqual(t0.OwnedTechs.OrderBy(x => x)),
        "TeamState: lists are sorted (byte-deterministic)",
        "TeamState unsorted"
    );
}
{
    int b0 = world.Bases.FindIndex(b => b.Team == 0);
    world.ResearchByBase[b0].Active.Add((3, 100, 400));
    world.ResearchByBase[b0].Active.Add((5, 120, 800));
    world.ResearchByBase[b0].OnDeck = 9;
    var rs = ResearchStateMessage.Parse(Protocol.BuildResearchStateFor(world, 0));
    Check(
        rs.Bases.Length == 1
            && rs.Bases[0].BaseId == world.Bases[b0].Id
            && rs.Bases[0].Active.Length == 2
            && rs.Bases[0].Active[1].DevIndex == 5
            && rs.Bases[0].Active[1].DurationTicks == 800
            && rs.Bases[0].OnDeck == 9,
        "ResearchStateFor team 0: active slots + on-deck",
        "ResearchState team 0"
    );
    Check(
        ResearchStateMessage.Parse(Protocol.BuildResearchStateFor(world, 1)).Bases.Length == 0,
        "ResearchStateFor team 1: idle → empty",
        "ResearchState team 1"
    );
}
vision.Ghosts[900] = new Simulation.GhostContact
{
    ShipId = 900,
    Team = 1,
    Cls = 2,
    Sector = 4,
    Pos = new Vec3(100f, 200f, 300f),
    Yaw = 2.9f,
    Pitch = -1.2f,
};
vision.Ghosts[901] = new Simulation.GhostContact
{
    ShipId = 901,
    Team = 1,
    Cls = 0,
    Sector = 4,
    Pos = new Vec3(-1f, -2f, -3f),
    Yaw = -3.5f, // beyond ±pi: clamps
    Pitch = 1.7f, // beyond ±pi/2: clamps
};
vision.VisibleEnemyShips.Add(900);
vision.VisibleEnemyShips.Add(12345);
{
    var c = ContactsMessage.Parse(Protocol.BuildContacts(vision));
    var g0 = c.Ghosts.First(g => g.ShipId == 900);
    var g1 = c.Ghosts.First(g => g.ShipId == 901);
    Check(
        c.Ghosts.Length == 2 && c.Radar.Length == 2 && c.Radar.Contains(900UL) && c.Radar.Contains(12345UL),
        "Contacts: ghosts + radar ids",
        "Contacts counts"
    );
    Check(
        g0.Team == 1
            && g0.Cls == 2
            && g0.Sector == 4
            && g0.Pos.X == 100f
            && Near(g0.Yaw, 2.9f, 1e-3f)
            && Near(g0.Pitch, -1.2f, 1e-3f),
        "Contacts: ghost pos exact, yaw/pitch within i16 quantization",
        "Contacts ghost 900"
    );
    Check(
        Near(g1.Yaw, -MathF.PI, 1e-3f) && Near(g1.Pitch, MathF.PI / 2f, 1e-3f),
        "Contacts: out-of-range yaw/pitch clamp to ±range",
        $"clamp yaw {g1.Yaw} pitch {g1.Pitch}"
    );
}

// Loadouts: spawn two scouts (the fighter is tech-locked at match start), override one, load a hold.
sim.EnqueueJoin(1, 0, 0, Array.Empty<(uint, byte)>(), 0, null);
sim.EnqueueJoin(2, 1, 0, Array.Empty<(uint, byte)>(), 0, null);
sim.Step();
{
    var flown = sim.Ships.Where(s => s.OwnerClientId >= 1 && !s.IsPod).ToList();
    Check(flown.Count == 2, "two hulls spawned for the loadout frame", $"spawned {flown.Count}");
    if (flown.Count == 2)
    {
        flown[0].MountWeaponIds = new uint[] { 0, HardpointDef.NoWeapon };
        flown[1].Hold = new List<(byte Kind, uint ItemId, byte Count)> { (2, 3, 6), (0, 9, 1), (1, 5, 2) };
        var parsed = ShipLoadoutMessage.Parse(Protocol.BuildShipLoadouts(sim));
        var r0 = parsed.Ships.First(r => r.ShipId == flown[0].ShipId);
        var r1 = parsed.Ships.First(r => r.ShipId == flown[1].ShipId);
        Check(
            parsed.Ships.Length == 2
                && r0.WeaponIds.SequenceEqual(new uint[] { 0, HardpointDef.NoWeapon })
                && r0.Hold.Length == 0,
            "ShipLoadouts: override row carries the effective ids + empty hold",
            "loadout override row"
        );
        Check(
            r1.Hold.Length == 3
                && r1.Hold[0].Kind == 2
                && r1.Hold[0].ItemId == 3
                && r1.Hold[0].Count == 6
                && r1.WeaponIds.Length > 0
                && r1.WeaponIds.SequenceEqual(
                    content
                        .Ships.First(d => d.ClassId == 0)
                        .Hardpoints.Where(h => h.Kind == HardpointKind.Weapon)
                        .Select(h => h.WeaponId)
                ),
            "ShipLoadouts: hold-only row streams the AUTHORED ids + its hold",
            "loadout hold row"
        );
        flown[0].MountWeaponIds = null;
        flown[1].Hold = null;
    }
    Check(
        ShipLoadoutMessage.Parse(Protocol.BuildShipLoadouts(sim)).Ships.Length == 0,
        "ShipLoadouts: no rows → empty frame (still sent, prunes by omission)",
        "loadout empty"
    );
}
{
    var cb = Protocol.BuildConstructorBuilds(sim);
    Check(
        cb is not null && ConstructorBuildsMessage.Parse(cb).Builds.Length == 0,
        "ConstructorBuilds: idle inside the grace window → empty frame (not null)",
        "ConstructorBuilds grace"
    );
    for (int i = 0; i < 40; i++)
        sim.Step();
    Check(
        Protocol.BuildConstructorBuilds(sim) is null,
        "ConstructorBuilds: idle past the grace window → no frame",
        "ConstructorBuilds past grace"
    );
}
{
    var station = content.StationCatalog.FirstOrDefault(s => s.BaseTypeId >= 0 && s.Price >= 0);
    if (station is not null)
    {
        world.TeamStates[0].Credits += 1_000_000;
        sim.EnqueueConstructorBuy(0, (byte)station.BaseTypeId, 0);
        sim.Step();
    }
    var view = sim.ConstructorStatesView();
    var cs0 = ConstructorStateMessage.Parse(Protocol.BuildConstructorState(sim, 0));
    var cs1 = ConstructorStateMessage.Parse(Protocol.BuildConstructorState(sim, 1));
    Console.WriteLine($"      constructor roster rows: {view.Count}");
    Check(
        cs0.Constructors.Length == view.Count(r => r.Team == 0) && cs1.Constructors.Length == view.Count(r => r.Team == 1),
        "ConstructorState: per-team row counts match the sim view",
        "ConstructorState counts"
    );
    if (view.Count > 0 && cs0.Constructors.Length > 0)
        Check(
            cs0.Constructors[0].Id == view[0].Id
                && cs0.Constructors[0].StationTypeId == view[0].StationType
                && cs0.Constructors[0].State == view[0].State
                && cs0.Constructors[0].LaunchBaseId == view[0].LaunchBaseId,
            "ConstructorState: row fields mirror the view",
            "ConstructorState row"
        );
}
Check(Protocol.BuildMinerTargets(sim) is null, "MinerTargets: null when nothing mines", "MinerTargets");

// Defs: the whole content bundle, field for field.
{
    var d = DefsMessage.Parse(Protocol.BuildDefs(content));
    Check(
        d.Ships.Count == content.Ships.Count
            && d.Weapons.Count == content.Weapons.Count
            && d.CargoItems.Count == content.CargoItems.Count
            && d.Bases.Count == content.Bases.Count
            && d.Techs.Count == content.Techs.Count
            && d.Developments.Count == content.Developments.Count
            && d.Stations.Count == content.StationCatalog.Count
            && d.FactionName == content.Start.FactionName
            && d.FactionAttributes.Length == content.Start.BaseAttributes.Length,
        "Defs (stock bundle): every catalog count + faction identity",
        "Defs counts"
    );
    for (int i = 0; i < content.Ships.Count; i++)
    {
        var a = d.Ships[i];
        var c = content.Ships[i];
        if (
            !(
                a.ClassId == c.ClassId
                && a.Name == c.Name
                && a.ModelName == c.ModelName
                && a.Mass == c.Mass
                && a.MaxSpeed == c.MaxSpeed
                && a.MaxHull == c.MaxHull
                && a.ShieldCapacity == c.ShieldCapacity
                && a.Cost == c.Cost
                && a.PayloadCapacity == c.PayloadCapacity
                && a.FactionId == c.FactionId
                && a.Hardpoints.Count == c.Hardpoints.Count
                && a.DefaultCargo.Count == c.DefaultCargo.Count
                && a.IsConstructor == c.IsConstructor
                && a.RequiredTechIdx.SequenceEqual(c.RequiredTechIdx)
                && a.LaunchClassMask == c.LaunchClassMask
                && a.CargoCapacity == Math.Clamp(c.CargoCapacity, 0, 255)
                && a.SignatureBias == 0f
            )
        )
        {
            Check(false, "", $"Defs: ship {c.Name} did not survive the round-trip");
            break;
        }
        if (i == content.Ships.Count - 1)
            Check(
                true,
                $"Defs: all {content.Ships.Count} ship defs survive the round-trip ([WireIgnore] SignatureBias dropped)",
                ""
            );
    }
    for (int i = 0; i < content.Weapons.Count; i++)
    {
        var a = d.Weapons[i];
        var c = content.Weapons[i];
        if (
            !(
                a.WeaponId == c.WeaponId
                && a.Name == c.Name
                && a.Damage == c.Damage
                && a.Kind == c.Kind
                && a.MagazineSize == c.MagazineSize
                && a.ModelName == c.ModelName
                && a.CargoId == c.CargoId
                && a.ShieldMult == c.ShieldMult
                && a.RequiredTechIdx.SequenceEqual(c.RequiredTechIdx)
                && a.ObsoletedByTechIdx.SequenceEqual(c.ObsoletedByTechIdx)
                && a.SucceededByWeaponId == c.SucceededByWeaponId
                && a.ReloadTicks == c.ReloadTicks
                && a.RoundMass == c.RoundMass
                && a.MineSignature == 0f
                && a.ProbeHitPoints == 0f
                && a.ProbeSignature == 0f
            )
        )
        {
            Check(false, "", $"Defs: weapon {c.Name} did not survive the round-trip");
            break;
        }
        if (i == content.Weapons.Count - 1)
            Check(
                true,
                $"Defs: all {content.Weapons.Count} weapon defs survive the round-trip (server-only fields dropped)",
                ""
            );
    }
    var dv = d
        .Developments.Zip(content.Developments)
        .All(p =>
            p.First.Id == p.Second.Id
            && p.First.Price == p.Second.Price
            && p.First.GrantedTechIdx.SequenceEqual(p.Second.GrantedTechIdx)
            && p.First.Attributes.SequenceEqual(p.Second.Attributes)
            && p.First.UpgradeScope == p.Second.UpgradeScope
        );
    var stn = d
        .Stations.Zip(content.StationCatalog)
        .All(p =>
            p.First.Id == p.Second.Id
            && p.First.BaseTypeId == p.Second.BaseTypeId
            && p.First.SuccessorBaseTypeId == p.Second.SuccessorBaseTypeId
            && p.First.AlignTimeSeconds == p.Second.AlignTimeSeconds
            && p.First.GrantedCaps.SequenceEqual(p.Second.GrantedCaps)
        );
    var bs = d
        .Bases.Zip(content.Bases)
        .All(p =>
            p.First.BaseTypeId == p.Second.BaseTypeId
            && p.First.Name == p.Second.Name
            && p.First.MaxHealth == p.Second.MaxHealth
            && p.First.Hardpoints.Count == p.Second.Hardpoints.Count
            && p.First.ModelName == p.Second.ModelName
            && p.First.WinCondition == p.Second.WinCondition
            && p.First.SuccessorBaseTypeId == p.Second.SuccessorBaseTypeId
        );
    Check(
        dv && stn && bs,
        "Defs: developments / station catalog / base defs survive the round-trip",
        "Defs dev/station/base"
    );
    Check(
        d.World.SectorScale == content.World.SectorScale
            && d.World.FogOfWar == content.World.FogOfWar
            && d.World.AsteroidDensity == content.World.AsteroidDensity,
        "Defs: the streamed world-config slice",
        "Defs world slice"
    );
}
{
    var maps = MapLoader.LoadAvailable(mapsDir, null);
    var catalog = MapCatalog.Build(maps, content.World, 7, content.Bases[0].MaxHealth, content.Start, content.Ships);
    Console.WriteLine($"      map catalog: {catalog.Count} maps");
    var parsed = MapListMessage.Parse(Protocol.BuildMapList(catalog));
    bool ok = parsed.Maps.Length == catalog.Count;
    for (int i = 0; ok && i < catalog.Count; i++)
    {
        var a = parsed.Maps[i];
        var c = catalog[i];
        ok =
            a.Name == c.Name
            && a.Mode == c.Mode
            && a.SizeLabel == c.SizeLabel
            && a.SectorLabel == c.SectorLabel
            && a.GarrisonCount == c.GarrisonCount
            && a.Sectors.Length == c.Sectors.Count
            && a.Links.Length == c.Links.Count;
        for (int s = 0; ok && s < c.Sectors.Count; s++)
            ok =
                a.Sectors[s].Id == c.Sectors[s].Id
                && a.Sectors[s].Name == c.Sectors[s].Name
                && (a.Sectors[s].MapPos is not null) == c.Sectors[s].HasMapPos
                && a.Sectors[s].BaseTeams.SequenceEqual(c.Sectors[s].Bases.Select(b => b.Team));
    }
    Check(ok, $"MapList: all {catalog.Count} maps, sectors, garrison teams and links survive", "MapList fields");
}
{
    var roster = new List<LobbyEntry>
    {
        new(1, "alpha", 0, true, true, 42UL),
        new(2, "βeta", 1, false, false, 0UL),
        new(3, "gamma", Wire.NoTeam, false, false, 0UL),
    };
    var lb = LobbyStateMessage.Parse(
        Protocol.BuildLobbyState(1, 0, roster, new[] { ("BLUE", 1), ("RED TEAM", -1) }, 1, "Brimstone Gambit")
    );
    Check(
        lb.Phase == 1
            && lb.Winner == 0
            && lb.Players.Length == 3
            && lb.Players[1].Name == "βeta"
            && lb.Players[0].Ready
            && lb.Players[0].HasShip
            && lb.Players[0].ShipId == 42
            && lb.Players[2].Team == Wire.NoTeam
            && lb.Teams.Length == 2
            && lb.Teams[0].Name == "BLUE"
            && lb.Teams[0].Commander == 1
            && lb.Teams[1].Name == "RED TEAM"
            && lb.Teams[1].Commander == -1
            && lb.HostId == 1
            && lb.SelectedMap == "Brimstone Gambit",
        "LobbyState: roster rows + session-global tail",
        "LobbyState fields"
    );
    var rows = new List<Protocol.StatsEntry>
    {
        new(1, "alpha", 0, true, 7, 2, 3, 675),
        new(2, "βeta", 1, false, 70000, 1, 0, -25), // kills clamp to u16
        new(9, "Pilot9", Wire.NoTeam, false, 0, 0, 0, 0),
    };
    var teams = new (byte, int, int)[] { (0, 1, 300), (1, 0, 2) }; // outposts clamp to u8
    var ms = MatchStatsMessage.Parse(Protocol.BuildMatchStats(rows, teams));
    Check(
        ms.Pilots.Length == 3
            && ms.Pilots[0].Kills == 7
            && ms.Pilots[0].Points == 675
            && ms.Pilots[0].Connected
            && ms.Pilots[1].Kills == 65535
            && !ms.Pilots[1].Connected
            && ms.Pilots[1].Points == -25
            && ms.Pilots[1].Name == "βeta"
            && ms.Teams.Length == 2
            && ms.Teams[0].Outposts == 255
            && ms.Teams[0].Garrisons == 1
            && ms.Teams[1].Outposts == 2,
        "MatchStats: rows, u16/u8 clamps, signed points, LEFT flag",
        "MatchStats fields"
    );
}

// ================================================================================================
// 4. Hello: every field optional, shorter (older) frames parse with the rest ""
// ================================================================================================
Console.WriteLine("---- 4. Hello ----");
{
    string secret = "s3cret",
        name = "Zoë Pilot",
        recon = "0123456789ABCDEF0123456789ABCDEF",
        join = new string('j', 350);
    byte[] full = new HelloMessage
    {
        Secret = secret,
        Name = name,
        ReconnectToken = recon,
        JoinToken = join,
    }.ToBytes();
    var f = HelloMessage.Parse(full);
    Check(
        f.Secret == secret && f.Name == name && f.ReconnectToken == recon && f.JoinToken == join,
        "Hello: all four fields round-trip (350 B join token)",
        "Hello full"
    );
    Check(
        new HelloMessage { Name = "smoke" }
            .ToBytes()
            .AsSpan()
            .SequenceEqual(new byte[] { 1, 0, 5, (byte)'s', (byte)'m', (byte)'o', (byte)'k', (byte)'e', 0, 0, 0 }),
        "Hello: proto-38 layout [id][u8 secret][u8 name][u8 token][u16 join]",
        "Hello layout"
    );

    // Well-formed prefixes: the fields present parse, the rest read as "".
    int o = 1;
    int afterSecret = o + 1 + Encoding.UTF8.GetByteCount(secret);
    int afterName = afterSecret + 1 + Encoding.UTF8.GetByteCount(name);
    int afterToken = afterName + 1 + Encoding.UTF8.GetByteCount(recon);
    Check(
        HelloMessage.TryParse(full.AsSpan(0, 1), out var h0)
            && h0.Secret == ""
            && h0.Name == ""
            && h0.ReconnectToken == ""
            && h0.JoinToken == "",
        "Hello prefix: bare id byte → every field \"\"",
        "Hello bare"
    );
    Check(
        HelloMessage.TryParse(full.AsSpan(0, afterSecret), out var h1)
            && h1.Secret == secret
            && h1.Name == ""
            && h1.ReconnectToken == ""
            && h1.JoinToken == "",
        "Hello prefix: secret only",
        "Hello secret-only"
    );
    Check(
        HelloMessage.TryParse(full.AsSpan(0, afterName), out var h2)
            && h2.Secret == secret
            && h2.Name == name
            && h2.ReconnectToken == ""
            && h2.JoinToken == "",
        "Hello prefix: secret + name (v7 shape)",
        "Hello v7"
    );
    Check(
        HelloMessage.TryParse(full.AsSpan(0, afterToken), out var h3) && h3.ReconnectToken == recon && h3.JoinToken == "",
        "Hello prefix: + reconnect token (v9 shape, no join tail)",
        "Hello v9"
    );
    // A field cut mid-string is "absent", never a parse failure; earlier fields survive.
    Check(
        HelloMessage.TryParse(full.AsSpan(0, afterSecret + 3), out var mid) && mid.Secret == secret && mid.Name == "",
        "Hello: a name cut mid-string reads as absent (still a valid frame)",
        "Hello mid-field truncation"
    );
    Check(
        HelloMessage.TryParse(full.AsSpan(0, full.Length - 7), out var tj)
            && tj.ReconnectToken == recon
            && tj.JoinToken == "",
        "Hello: a torn join token is ignored, earlier fields survive",
        "Hello torn join"
    );
    // The frames the hub-level tests and the bot hand-build / used to hand-build.
    var smoke = new List<byte> { HelloMessage.MsgId, 0, 5 };
    smoke.AddRange(Encoding.UTF8.GetBytes("smoke"));
    smoke.Add(0);
    Check(
        HelloMessage.TryParse(smoke.ToArray(), out var sm)
            && sm.Name == "smoke"
            && sm.Secret == ""
            && sm.ReconnectToken == ""
            && sm.JoinToken == "",
        "Hello: the tests' 8-byte smoke frame parses",
        "smoke Hello"
    );
    Check(
        HelloMessage.TryParse(new byte[] { 1, 0, 0 }, out var v7) && v7.Name == "" && v7.JoinToken == "",
        "Hello: the old 3-byte simbot frame parses",
        "v7 Hello"
    );
    bool threw = false;
    try
    {
        _ = new HelloMessage { Secret = new string('x', 300) }.ToBytes();
    }
    catch (ArgumentException)
    {
        threw = true;
    }
    Check(threw, "Hello: a u8-length field over 255 bytes throws at build (never a silent wrap)", "Hello oversize build");
}

// ================================================================================================
// 5. client -> server frames: the Godot client's hand-packed layouts, replicated here
// ================================================================================================
Console.WriteLine("---- 5. client->server layouts ----");
{
    var input = new ShipInputState
    {
        Thrust = 0.75f,
        StrafeX = -0.5f,
        StrafeY = 0.25f,
        Yaw = -1f,
        Pitch = 0.125f,
        Roll = 1f,
        Firing = true,
        Boost = false,
        Firing2 = true,
        DropChaff = false,
        DropMine = true,
        DropProbe = true,
        LockTargetId = 0x0102030405060708UL,
    };
    // GameNetClient.SendInput, verbatim.
    var f = new byte[38];
    f[0] = 2;
    BitConverter.TryWriteBytes(f.AsSpan(1), 777u);
    BitConverter.TryWriteBytes(f.AsSpan(5), input.Thrust);
    BitConverter.TryWriteBytes(f.AsSpan(9), input.StrafeX);
    BitConverter.TryWriteBytes(f.AsSpan(13), input.StrafeY);
    BitConverter.TryWriteBytes(f.AsSpan(17), input.Yaw);
    BitConverter.TryWriteBytes(f.AsSpan(21), input.Pitch);
    BitConverter.TryWriteBytes(f.AsSpan(25), input.Roll);
    f[29] = (byte)(
        (input.Firing ? 1 : 0)
        | (input.Boost ? 2 : 0)
        | (input.Firing2 ? 4 : 0)
        | (input.DropChaff ? 8 : 0)
        | (input.DropMine ? 16 : 0)
        | (input.DropProbe ? 32 : 0)
    );
    BitConverter.TryWriteBytes(f.AsSpan(30), input.LockTargetId);
    Same("Input (client layout)", f, InputMessage.From(777, input).ToBytes());
    var back = InputMessage.Parse(f).ToInput();
    Check(
        back.Thrust == input.Thrust
            && back.Yaw == input.Yaw
            && back.Firing == input.Firing
            && back.Boost == input.Boost
            && back.Firing2 == input.Firing2
            && back.DropChaff == input.DropChaff
            && back.DropMine == input.DropMine
            && back.DropProbe == input.DropProbe
            && back.LockTargetId == input.LockTargetId,
        "Input: ToInput restores every stick and flag",
        "Input round-trip"
    );
}
{
    // GameNetClient.RequestSpawn, verbatim.
    var cargo = new (uint cargoId, byte count)[] { (2u, 3), (5u, 1) };
    var mounts = new (byte hpIndex, uint weaponId)[] { (1, uint.MaxValue), (0, 9u) };
    var f = new byte[11 + cargo.Length * 5 + 1 + mounts.Length * 5];
    int o = 0;
    f[o++] = 4;
    f[o++] = 3;
    BitConverter.TryWriteBytes(f.AsSpan(o), 0xB00BUL);
    o += 8;
    f[o++] = (byte)cargo.Length;
    foreach (var (cargoId, count) in cargo)
    {
        BitConverter.TryWriteBytes(f.AsSpan(o), cargoId);
        o += 4;
        f[o++] = count;
    }
    f[o++] = (byte)mounts.Length;
    foreach (var (hpIndex, weaponId) in mounts)
    {
        f[o++] = hpIndex;
        BitConverter.TryWriteBytes(f.AsSpan(o), weaponId);
        o += 4;
    }
    var msg = new SpawnMessage
    {
        ShipClass = 3,
        LaunchBaseId = 0xB00BUL,
        Cargo = new[]
        {
            new CargoLoadDef { CargoId = 2, Count = 3 },
            new CargoLoadDef { CargoId = 5, Count = 1 },
        },
        Mounts = new[]
        {
            new MountOverrideRecord { HpIndex = 1, WeaponId = uint.MaxValue },
            new MountOverrideRecord { HpIndex = 0, WeaponId = 9 },
        },
    };
    Same("Spawn (client layout, cargo + mounts)", f, msg.ToBytes());
    Check(
        SpawnMessage.TryParse(f, out var sp)
            && sp.Cargo.Length == 2
            && sp.Mounts.Length == 2
            && sp.Mounts[0].WeaponId == uint.MaxValue
            && sp.LaunchBaseId == 0xB00BUL,
        "Spawn parses cargo + mounts",
        "Spawn parse"
    );
    // ClientHub today: a bare 10-byte frame = no cargo, no mounts; cargo-only = mounts empty; a tail
    // whose element bytes are missing is IGNORED (not a protocol error).
    Check(
        SpawnMessage.TryParse(f.AsSpan(0, 10), out var bare)
            && bare.ShipClass == 3
            && (bare.Cargo?.Length ?? 0) == 0
            && (bare.Mounts?.Length ?? 0) == 0,
        "Spawn: bare 10-byte frame → hull default cargo + authored loadout",
        "Spawn bare"
    );
    Check(
        SpawnMessage.TryParse(f.AsSpan(0, 21), out var cargoOnly)
            && cargoOnly.Cargo.Length == 2
            && (cargoOnly.Mounts?.Length ?? 0) == 0,
        "Spawn: cargo block without a mount tail → zero overrides",
        "Spawn cargo-only"
    );
    Check(
        SpawnMessage.TryParse(f.AsSpan(0, 25), out var torn) && torn.Cargo.Length == 2 && (torn.Mounts?.Length ?? 0) == 0,
        "Spawn: a torn mount tail is ignored (cargo kept, no overrides)",
        "Spawn torn tail"
    );
    var legacySmoke = new byte[] { Protocol.MsgSpawn, 0, 0, 0, 0, 0, 0, 0, 0, 0 }; // SalvageTest's join frame
    Check(
        SpawnMessage.TryParse(legacySmoke, out var ls) && ls.ShipClass == 0 && ls.LaunchBaseId == 0,
        "Spawn: the hub tests' 10-byte scout frame parses",
        "Spawn smoke"
    );
}
{
    var pos = new Vec3(1.5f, -2.5f, 1000f);
    var f = new byte[27];
    f[0] = 11;
    f[1] = 1;
    f[2] = 3;
    BitConverter.TryWriteBytes(f.AsSpan(3), 0x55UL);
    BitConverter.TryWriteBytes(f.AsSpan(11), 6u);
    BitConverter.TryWriteBytes(f.AsSpan(15), pos.X);
    BitConverter.TryWriteBytes(f.AsSpan(19), pos.Y);
    BitConverter.TryWriteBytes(f.AsSpan(23), pos.Z);
    Same(
        "SetAutopilot (client layout)",
        f,
        new SetAutopilotMessage
        {
            Mode = 1,
            Kind = 3,
            Id = 0x55,
            Sector = 6,
            Pos = pos,
        }.ToBytes()
    );
    var g = new byte[34];
    g[0] = 12;
    BitConverter.TryWriteBytes(g.AsSpan(1), 0xAAUL);
    g[9] = 4;
    BitConverter.TryWriteBytes(g.AsSpan(10), 0xBBUL);
    BitConverter.TryWriteBytes(g.AsSpan(18), 2u);
    BitConverter.TryWriteBytes(g.AsSpan(22), pos.X);
    BitConverter.TryWriteBytes(g.AsSpan(26), pos.Y);
    BitConverter.TryWriteBytes(g.AsSpan(30), pos.Z);
    Same(
        "Order (client layout)",
        g,
        new OrderMessage
        {
            SubjectShipId = 0xAA,
            TargetKind = 4,
            TargetId = 0xBB,
            Sector = 2,
            Pos = pos,
        }.ToBytes()
    );
    var r = new byte[12];
    r[0] = 13;
    r[1] = 2;
    BitConverter.TryWriteBytes(r.AsSpan(2), 0xCCUL);
    BitConverter.TryWriteBytes(r.AsSpan(10), (ushort)7);
    Same(
        "Research (client layout)",
        r,
        new ResearchMessage
        {
            Op = 2,
            BaseId = 0xCC,
            DevIndex = 7,
        }.ToBytes()
    );
    var bc = new byte[10];
    bc[0] = 14;
    bc[1] = 5;
    BitConverter.TryWriteBytes(bc.AsSpan(2), 0xDDUL);
    Same(
        "BuildConstructor (client layout)",
        bc,
        new BuildConstructorMessage { StationTypeId = 5, LaunchBaseId = 0xDD }.ToBytes()
    );
    var cc = new byte[9];
    cc[0] = 15;
    BitConverter.TryWriteBytes(cc.AsSpan(1), 0xEEUL);
    Same("ConstructorCancel (client layout)", cc, new ConstructorCancelMessage { ConstructorId = 0xEE }.ToBytes());
    var bm = new byte[9];
    bm[0] = 16;
    BitConverter.TryWriteBytes(bm.AsSpan(1), 0xFFUL);
    Same("BuyMiner (client layout)", bm, new BuyMinerMessage { LaunchBaseId = 0xFF }.ToBytes());
    Same("SetTeam (client layout)", new byte[] { 5, 1 }, new SetTeamMessage { Team = 1 }.ToBytes());
    Same("SetReady (client layout)", new byte[] { 6, 1 }, new SetReadyMessage { Ready = true }.ToBytes());
    Same("Bye (client layout)", new byte[] { 8 }, new ByeMessage().ToBytes());
    var pingRef = new byte[5];
    pingRef[0] = 3;
    BitConverter.TryWriteBytes(pingRef.AsSpan(1), 0x1234u);
    Same("Ping (client layout)", pingRef, new PingMessage { Nonce = 0x1234 }.ToBytes());
    var t = Encoding.UTF8.GetBytes("gg wp ✈");
    var chat = new byte[4 + t.Length];
    chat[0] = 7;
    chat[1] = 1;
    BitConverter.TryWriteBytes(chat.AsSpan(2), (ushort)t.Length);
    t.CopyTo(chat, 4);
    Same("Chat (client layout)", chat, new ChatMessage { Scope = 1, Text = "gg wp ✈" }.ToBytes());
    var n = Encoding.UTF8.GetBytes("IRON COALITION");
    var tn = new byte[4 + n.Length];
    tn[0] = 9;
    tn[1] = 0;
    BitConverter.TryWriteBytes(tn.AsSpan(2), (ushort)n.Length);
    n.CopyTo(tn, 4);
    Same("SetTeamName (client layout)", tn, new SetTeamNameMessage { Team = 0, Name = "IRON COALITION" }.ToBytes());
    var m = Encoding.UTF8.GetBytes("Kestrel Cross");
    var sm = new byte[3 + m.Length];
    sm[0] = 10;
    BitConverter.TryWriteBytes(sm.AsSpan(1), (ushort)m.Length);
    m.CopyTo(sm, 3);
    Same("SetMap (client layout)", sm, new SetMapMessage { MapName = "Kestrel Cross" }.ToBytes());
}

// ================================================================================================
// 6. Synthetic round-trips
// ================================================================================================
Console.WriteLine("---- 6. round-trips ----");
void RoundTrip<T>(string what, byte[] bytes, Func<byte[], T> parse, Func<T, byte[]> write)
{
    var v = parse(bytes);
    var again = write(v);
    Check(
        bytes.AsSpan().SequenceEqual(again),
        $"{what}: write → read → write is byte-stable ({bytes.Length} B)",
        $"{what}: re-written bytes differ: {Diff(bytes, again)}"
    );
}

var longName = new string('n', 300); // 7-bit length prefix needs two bytes past 127
var synthSector = new SectorStatic
{
    Id = 9,
    Radius = 1575f,
    Name = longName,
    MapPos = new MapPosRecord { X = -0.5f, Y = 0.75f },
    Env = new SectorEnvWire
    {
        Sun = new SunEnvWire
        {
            GodRays = 0.4f,
            Dir = new Vec3(0f, 0.7f, 0.7f),
            Color = new Vec3(1f, 0.9f, 0.8f),
            Energy = 2f,
            Ambient = 0.3f,
            DiscSize = 900f,
        },
        Nebula = new NebulaEnvWire
        {
            ColorA = new Vec3(0.1f, 0.2f, 0.3f),
            ColorB = SectorEnvWire.NoColor,
            Intensity = -1f,
            Seed = 12345u,
        },
        Dust = new DustEnvWire
        {
            Color = SectorEnvWire.NoColor,
            Opacity = 0.5f,
            Clouds = new[]
            {
                new DustCloudWire
                {
                    Pos = new Vec3(1f, 2f, 3f),
                    Radius = 400f,
                    Density = 0.8f,
                },
            },
        },
    },
};
var synthWelcome = new WelcomeMessage
{
    Version = 40, // a literal, not Wire.ProtocolVersion: the golden pins the LAYOUT, not the current version
    ClientId = 5,
    Team = 0,
    Tick = 99,
    Dt = 0.05f,
    ReconnectToken = new byte[] { 1, 2, 3, 4 },
    Sectors = new[]
    {
        synthSector,
        new SectorStatic
        {
            Id = 10,
            Radius = 700f,
            Name = "",
            MapPos = null,
            Env = new SectorEnvWire(),
        },
    },
    Bases = new[]
    {
        new BaseStatic
        {
            Id = 1,
            Team = 0,
            Sector = 9,
            Pos = new Vec3(10f, 20f, 30f),
            Radius = 120f,
            Health = 5000f,
            BaseTypeId = 0,
        },
    },
    Rocks = new[]
    {
        new RockStatic
        {
            Id = 2,
            Sector = 9,
            Pos = new Vec3(-1f, -2f, -3f),
            Radius = 40f,
            Variant = 3,
            RotX = 0.1f,
            RotY = 0.2f,
            RotZ = 0.3f,
            RockClass = 4,
            CurrentRadius = 33f,
            OrePct = 82,
            OreCapacity = 12000f,
        },
    },
    Alephs = new[]
    {
        new AlephStatic
        {
            Id = 3,
            Sector = 9,
            DestSector = 10,
            Pos = new Vec3(500f, 0f, -500f),
        },
    },
};
RoundTrip(
    "Welcome (synthetic: env blocks, long 7-bit name, empty sector)",
    synthWelcome.ToBytes(),
    b => WelcomeMessage.Parse(b),
    v => v.ToBytes()
);
{
    var v = WelcomeMessage.Parse(synthWelcome.ToBytes());
    Check(
        v.Sectors[0].Name == longName
            && v.Sectors[0].Env.Nebula!.Seed == 12345u
            && v.Sectors[0].Env.Dust!.Clouds.Length == 1
            && v.Sectors[1].MapPos is null
            && !v.Sectors[1].Env.Any,
        "Welcome (synthetic): nullable blocks + 7-bit name decode",
        "Welcome synthetic fields"
    );
}
RoundTrip(
    "Reveal (synthetic)",
    new RevealMessage
    {
        Bases = synthWelcome.Bases,
        Rocks = synthWelcome.Rocks,
        Alephs = synthWelcome.Alephs,
        Sectors = synthWelcome.Sectors,
    }.ToBytes(),
    b => RevealMessage.Parse(b),
    v => v.ToBytes()
);
var synthShips = ships.Select(Frames.ShipRecordOf).ToArray();
var synthSnapshot = new SnapshotMessage
{
    Tick = 1000,
    Phase = 1,
    Winner = 255,
    Ships = synthShips,
}.ToBytes();
RoundTrip("Snapshot (synthetic, 4 ships)", synthSnapshot, b => SnapshotMessage.Parse(b), v => v.ToBytes());
Check(
    synthSnapshot.Length == SnapshotMessage.HeaderSize + 4 * ShipRecord.Size,
    "Snapshot: header + N x ShipRecord.Size",
    "snapshot length"
);
RoundTrip(
    "Missiles (synthetic)",
    new MissilesMessage
    {
        Tick = 5,
        Missiles = new[] { Frames.MissileRecordOf(missile), Frames.MissileRecordOf(missile) },
    }.ToBytes(),
    b => MissilesMessage.Parse(b),
    v => v.ToBytes()
);
RoundTrip(
    "Minefields (synthetic)",
    new MinefieldsMessage { AnchorSector = 3, Fields = new[] { Frames.MinefieldRecordOf(field) } }.ToBytes(),
    b => MinefieldsMessage.Parse(b),
    v => v.ToBytes()
);
RoundTrip(
    "Minefields (empty)",
    new MinefieldsMessage { AnchorSector = 3, Fields = Array.Empty<MinefieldRecord>() }.ToBytes(),
    b => MinefieldsMessage.Parse(b),
    v => v.ToBytes()
);
RoundTrip(
    "Probes (synthetic)",
    new ProbesMessage { Probes = new[] { Frames.ProbeRecordOf(probe, 10) } }.ToBytes(),
    b => ProbesMessage.Parse(b),
    v => v.ToBytes()
);
RoundTrip(
    "Salvage (synthetic)",
    new SalvageMessage { AnchorSector = 5, Items = new[] { Frames.SalvageRecordOf(item, 1) } }.ToBytes(),
    b => SalvageMessage.Parse(b),
    v => v.ToBytes()
);
RoundTrip("Contacts (synthetic)", Frames.Contacts(vision).ToBytes(), b => ContactsMessage.Parse(b), v => v.ToBytes());
var synthTeamState = new TeamStateMessage
{
    Teams = new[]
    {
        new TeamStateRecord
        {
            Team = 0,
            Credits = -5,
            Score = 1200,
            UnlockedClasses = new byte[] { 0, 1, 3 },
            OwnedTechs = new ushort[] { 4, 9, 300 },
            OwnedCaps = new byte[] { 2 },
            DiscoveredRockClasses = 0x1F,
            MinerCount = 2,
            MinerCap = 4,
            BuildQueueLimit = 4,
        },
        new TeamStateRecord
        {
            Team = 1,
            Credits = 0,
            Score = 0,
            UnlockedClasses = Array.Empty<byte>(),
            OwnedTechs = Array.Empty<ushort>(),
            OwnedCaps = Array.Empty<byte>(),
            DiscoveredRockClasses = 0xFF,
            MinerCount = 0,
            MinerCap = 4,
            BuildQueueLimit = 4,
        },
    },
};
RoundTrip("TeamState (synthetic)", synthTeamState.ToBytes(), b => TeamStateMessage.Parse(b), v => v.ToBytes());
RoundTrip(
    "ResearchState (synthetic)",
    new ResearchStateMessage
    {
        Bases = new[]
        {
            new BaseResearchRecord
            {
                BaseId = 1,
                Active = new[]
                {
                    new ResearchActiveRecord
                    {
                        DevIndex = 3,
                        StartTick = 100,
                        DurationTicks = 400,
                    },
                },
                OnDeck = 9,
            },
            new BaseResearchRecord
            {
                BaseId = 2,
                Active = Array.Empty<ResearchActiveRecord>(),
                OnDeck = null,
            },
        },
    }.ToBytes(),
    b => ResearchStateMessage.Parse(b),
    v => v.ToBytes()
);
RoundTrip(
    "ConstructorState (synthetic)",
    new ConstructorStateMessage
    {
        Constructors = new[]
        {
            new ConstructorStateRecord
            {
                Id = 1,
                StationTypeId = 2,
                State = 5,
                StartTick = 10,
                DurationTicks = 20,
                TargetId = 30,
                ProducesMiner = true,
                LaunchBaseId = 40,
                ShipId = 50,
            },
        },
    }.ToBytes(),
    b => ConstructorStateMessage.Parse(b),
    v => v.ToBytes()
);
RoundTrip(
    "ConstructorBuilds (synthetic)",
    new ConstructorBuildsMessage
    {
        Builds = new[]
        {
            new ConstructorBuildRecord
            {
                ShipId = 1,
                RockId = 2,
                Phase = 1,
                Progress = 0.5f,
            },
        },
    }.ToBytes(),
    b => ConstructorBuildsMessage.Parse(b),
    v => v.ToBytes()
);
RoundTrip(
    "MinerTargets (synthetic)",
    new MinerTargetsMessage
    {
        Targets = new[]
        {
            new MinerTargetRecord { ShipId = 1, RockId = 2 },
        },
    }.ToBytes(),
    b => MinerTargetsMessage.Parse(b),
    v => v.ToBytes()
);
RoundTrip(
    "RockUpdate (synthetic)",
    new RockUpdateMessage
    {
        Rocks = new[]
        {
            new RockUpdateRecord
            {
                RockId = 1,
                CurrentRadius = 12.5f,
                OrePct = 40,
            },
        },
    }.ToBytes(),
    b => RockUpdateMessage.Parse(b),
    v => v.ToBytes()
);
RoundTrip(
    "RockGone (synthetic)",
    new RockGoneMessage { RockIds = new ulong[] { 1, 2, 3 } }.ToBytes(),
    b => RockGoneMessage.Parse(b),
    v => v.ToBytes()
);
RoundTrip(
    "Bases (synthetic)",
    new BasesMessage
    {
        Bases = new[]
        {
            new BaseHealthRecord { BaseId = 1, Health = 2f },
        },
    }.ToBytes(),
    b => BasesMessage.Parse(b),
    v => v.ToBytes()
);
RoundTrip(
    "ShipLoadout (synthetic)",
    new ShipLoadoutMessage
    {
        Ships = new[]
        {
            new ShipLoadoutRecord
            {
                ShipId = 1,
                WeaponIds = new uint[] { 0, uint.MaxValue },
                Hold = new[]
                {
                    new HoldItemRecord
                    {
                        Kind = 2,
                        ItemId = 3,
                        Count = 6,
                    },
                },
            },
        },
    }.ToBytes(),
    b => ShipLoadoutMessage.Parse(b),
    v => v.ToBytes()
);
var synthLobby = Frames
    .LobbyState(
        2,
        1,
        new List<LobbyEntry> { new(1, "α", 0, true, true, 9UL) },
        new[] { ("A", -1), ("B", 1), ("C", 7) },
        1,
        "map"
    )
    .ToBytes();
RoundTrip("LobbyState (synthetic)", synthLobby, b => LobbyStateMessage.Parse(b), v => v.ToBytes());
var synthStats = Frames
    .MatchStats(new List<Protocol.StatsEntry> { new(1, "a", 0, true, 1, 2, 3, 4) }, new (byte, int, int)[] { (0, 1, 2) })
    .ToBytes();
RoundTrip("MatchStats (synthetic)", synthStats, b => MatchStatsMessage.Parse(b), v => v.ToBytes());
var synthMaps = new MapListMessage
{
    Maps = new[]
    {
        new MapCatalogRecord
        {
            Name = "Test",
            Mode = "CONQUEST",
            SizeLabel = "S",
            SectorLabel = "3",
            GarrisonCount = 2,
            Sectors = new[]
            {
                new MapSectorRecord
                {
                    Id = 1,
                    Radius = 700f,
                    Name = "Home",
                    MapPos = new MapPosRecord { X = 0f, Y = 1f },
                    BaseTeams = new byte[] { 0 },
                },
                new MapSectorRecord
                {
                    Id = 2,
                    Radius = 900f,
                    Name = "",
                    MapPos = null,
                    BaseTeams = Array.Empty<byte>(),
                },
            },
            Links = new[]
            {
                new MapLinkRecord { A = 1, B = 2 },
            },
        },
    },
};
RoundTrip("MapList (synthetic)", synthMaps.ToBytes(), b => MapListMessage.Parse(b), v => v.ToBytes());
RoundTrip(
    "ChatRelay (synthetic)",
    Frames.ChatRelay(0, 1, "n", "t").ToBytes(),
    b => ChatRelayMessage.Parse(b),
    v => v.ToBytes()
);
RoundTrip("Reject", new RejectMessage { Code = 2 }.ToBytes(), b => RejectMessage.Parse(b), v => v.ToBytes());

// Synthetic defs: every def type with every list populated; ignored fields must not survive.
var synthDefs = new DefsMessage
{
    Ships = new List<ShipClassDef>
    {
        new()
        {
            ClassId = 1,
            Name = "Fighter",
            Glyph = "F",
            Role = "dogfighter",
            Description = "desc",
            ModelName = "p1_fig",
            ModelLength = 12f,
            Mass = 100f,
            MaxSpeed = 90f,
            Accel = 30f,
            RateYawDeg = 60f,
            RatePitchDeg = 70f,
            RateRollDeg = 120f,
            DriftYawDeg = 1f,
            DriftPitchDeg = 2f,
            SideMult = 0.4f,
            BackMult = 0.5f,
            AbAccel = 60f,
            AbOnRate = 2f,
            AbOffRate = 4f,
            MaxFuel = 50f,
            AbFuelDrain = 10f,
            AbFuelRecharge = 5f,
            MaxHull = 400f,
            ShieldCapacity = 100f,
            ShieldRecharge = 10f,
            ShieldDelaySec = 3f,
            VisionConeLength = 2000f,
            VisionConeAngleDeg = 30f,
            VisionSphereRadius = 500f,
            RadarSignature = 1.2f,
            SignatureBias = 5f,
            Cost = 300,
            PayloadCapacity = 12f,
            OreCapacity = 0f,
            OrderTimeSeconds = 0,
            FactionId = 7,
            IsConstructor = false,
            LaunchClassMask = 0b101,
            CargoCapacity = 300,
            RequiredTechIdx = new ushort[] { 1, 2 },
            Hardpoints = new List<HardpointDef>
            {
                new()
                {
                    Kind = HardpointKind.Weapon,
                    Index = 0,
                    OffX = 1f,
                    OffY = 2f,
                    OffZ = 3f,
                    DirX = 0f,
                    DirY = 0f,
                    DirZ = 1f,
                    WeaponId = 0,
                    Mount = WeaponMountKind.Gun,
                },
                new()
                {
                    Kind = HardpointKind.MainEngine,
                    Index = 1,
                    WeaponId = 0,
                },
            },
            DefaultCargo = new List<CargoLoadDef>
            {
                new() { CargoId = 2, Count = 3 },
            },
        },
    },
    Weapons = new List<WeaponDef>
    {
        new()
        {
            WeaponId = 3,
            Name = "Seeker",
            Damage = 50f,
            FireIntervalTicks = 20,
            ProjectileSpeed = 300f,
            ProjectileLifeTicks = 200,
            ProjectileRadius = 1f,
            SpreadRad = 0f,
            Mass = 4f,
            CanDamageBase = true,
            Kind = WeaponKind.Missile,
            MagazineSize = 6,
            LockTicks = 30,
            LockAngleRad = 0.5f,
            LockRange = 1500f,
            MissileAccel = 100f,
            MissileTurnRateRad = 2f,
            MissileMaxSpeed = 400f,
            BlastPower = 80f,
            BlastRadius = 30f,
            DirectHitMult = 1.5f,
            ModelName = "seeker",
            TrailLifetime = 1f,
            TrailScale = 1f,
            TrailColor = 0xFF8800FF,
            ChaffResistance = 0.5f,
            MineSignature = 9f,
            CargoId = 0,
            ShieldMult = 1f,
            ProbeHitPoints = 9f,
            ProbeSignature = 9f,
            RequiredTechIdx = new ushort[] { 4 },
            IsHealing = false,
            ObsoletedByTechIdx = new ushort[] { 5, 6 },
            SucceededByWeaponId = 12,
            ReloadTicks = 40,
            RoundMass = 4f,
        },
    },
    CargoItems = new List<CargoItemDef>
    {
        new()
        {
            CargoId = 5,
            Name = "Fuel Pod",
            Glyph = "⛽",
            Mass = 1f,
            ChargesPerPack = 1,
            Description = "d",
            FuelPerCharge = 30f,
            ReloadTicks = 60,
            ModelName = "pod",
        },
    },
    Bases = new List<BaseDef>
    {
        new()
        {
            BaseTypeId = 0,
            Name = "Garrison",
            Radius = 120f,
            MaxHealth = 5000f,
            VisionSphereRadius = 900f,
            RadarSignature = 3f,
            Hardpoints = new List<HardpointDef>(),
            ResearchSlots = 2,
            ModelName = "garrison",
            WinCondition = true,
            BuildRockClass = 255,
            SuccessorBaseTypeId = -1,
        },
    },
    World = new WorldConfigWire
    {
        Id = 0,
        SectorScale = 2.25f,
        AsteroidDensity = 1f,
        DebugFreezeBrain = false,
        DebugNoFire = true,
        FogOfWar = true,
    },
    Techs = new List<TechDef>
    {
        new()
        {
            Id = "t1",
            Name = "Tech 1",
            Description = "",
        },
    },
    Developments = new List<DevelopmentDef>
    {
        new()
        {
            Id = "d1",
            Name = "Dev 1",
            Description = "x",
            Group = "WEAPONS",
            Price = 500,
            BuildTimeSeconds = 60,
            TechOnly = true,
            RequiredTechIdx = new ushort[] { 0 },
            GrantedTechIdx = new ushort[] { 1 },
            ObsoletedByTechIdx = Array.Empty<ushort>(),
            RequiredCaps = new byte[] { 1 },
            GrantedCaps = Array.Empty<byte>(),
            UpgradeScope = 1,
            Attributes = new[] { new AttrMod(3, 1.25f), new AttrMod(7, 0.5f) },
        },
    },
    Stations = new List<StationCatalogDef>
    {
        new()
        {
            Id = "s1",
            Name = "Outpost",
            Description = "",
            Price = 1000,
            BuildTimeSeconds = 120,
            StationClass = 1,
            BaseTypeId = 1,
            ResearchSlots = 1,
            BuildRockClass = 2,
            AlignTimeSeconds = 5,
            RequiredTechIdx = Array.Empty<ushort>(),
            GrantedTechIdx = new ushort[] { 2 },
            ObsoletedByTechIdx = Array.Empty<ushort>(),
            RequiredCaps = Array.Empty<byte>(),
            GrantedCaps = new byte[] { 4 },
            SuccessorBaseTypeId = 2,
        },
    },
    FactionName = "Iron Coalition",
    FactionAttributes = new[] { new AttrMod(1, 1.1f) },
};
var synthDefsBytes = synthDefs.ToBytes();
RoundTrip("Defs (synthetic)", synthDefsBytes, b => DefsMessage.Parse(b), v => v.ToBytes());
{
    var d = DefsMessage.Parse(synthDefsBytes);
    Check(
        d.Ships[0].CargoCapacity == 255
            && d.Ships[0].SignatureBias == 0f
            && d.Weapons[0].MineSignature == 0f
            && d.Weapons[0].ProbeHitPoints == 0f
            && d.Developments[0].Attributes[1].Mult == 0.5f
            && d.Developments[0].Attributes[1].Attr == 7
            && d.Ships[0].Hardpoints[0].Mount == WeaponMountKind.Gun
            && d.Stations[0].SuccessorBaseTypeId == 2
            && d.World.FogOfWar
            && d.CargoItems[0].Glyph == "⛽",
        "Defs (synthetic): u8 clamp, ignored fields dropped, positional AttrMod, enums, i16 survive",
        "Defs synthetic fields"
    );
}

// ================================================================================================
// 7. Hostile input
// ================================================================================================
Console.WriteLine("---- 7. hostile input ----");
{
    var frames = new (string, byte[], Func<byte[], bool>)[]
    {
        ("Snapshot", synthSnapshot, b => SnapshotMessage.TryParse(b, out _)),
        ("Welcome", synthWelcome.ToBytes(), b => WelcomeMessage.TryParse(b, out _)),
        ("Defs", synthDefsBytes, b => DefsMessage.TryParse(b, out _)),
        ("TeamState", synthTeamState.ToBytes(), b => TeamStateMessage.TryParse(b, out _)),
        ("MapList", synthMaps.ToBytes(), b => MapListMessage.TryParse(b, out _)),
        ("LobbyState", synthLobby, b => LobbyStateMessage.TryParse(b, out _)),
        ("Input", InputMessage.From(1, default).ToBytes(), b => InputMessage.TryParse(b, out _)),
        ("Order", new OrderMessage().ToBytes(), b => OrderMessage.TryParse(b, out _)),
    };
    foreach (var (name, full, parse) in frames)
    {
        bool threw = false,
            accepted = false;
        for (int len = 0; len < full.Length; len++)
        {
            try
            {
                if (parse(full.AsSpan(0, len).ToArray()))
                    accepted = true;
            }
            catch
            {
                threw = true;
            }
        }
        Check(
            !threw && !accepted && parse(full),
            $"{name}: every truncated prefix rejected without throwing; the full frame parses",
            $"{name}: threw={threw} accepted-a-prefix={accepted}"
        );
    }
    // Count bombs: a u16/u32 count far beyond the bytes present must fail without allocating.
    var bomb = new byte[] { RevealMessage.MsgId, 0, 0xFF, 0xFF, 0, 0 };
    Check(
        !RevealMessage.TryParse(bomb, out _),
        "Reveal: 65535 rocks in a 6-byte frame is rejected",
        "reveal count bomb parsed"
    );
    var wbomb = new List<byte>
    {
        WelcomeMessage.MsgId,
        Wire.ProtocolVersion,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0 /*token 0*/
        ,
        0,
        0 /*sectors*/
        ,
        0,
        0 /*bases*/
        ,
        0xFF,
        0xFF,
        0xFF,
        0xFF,
    };
    Check(
        !WelcomeMessage.TryParse(wbomb.ToArray(), out _),
        "Welcome: a 4-billion rock count is rejected before any allocation",
        "welcome count bomb"
    );
    Check(
        !YouAreMessage.TryParse(new ShipGoneMessage { ShipId = 1 }.ToBytes(), out _),
        "wrong message id is rejected",
        "wrong id accepted"
    );
    bool parseThrew = false;
    try
    {
        _ = YouAreMessage.Parse(new byte[] { 2, 1, 2 });
    }
    catch (WireFormatException)
    {
        parseThrew = true;
    }
    Check(parseThrew, "Parse throws WireFormatException on a truncated frame", "Parse did not throw");
    var str7 = new byte[] { 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x7F };
    var r7 = new WireReader(str7);
    r7.Str7();
    Check(r7.Failed, "7-bit string length over 5 bytes fails", "7-bit overlong prefix accepted");
}

// ================================================================================================
// 8. Durable goldens
// ================================================================================================
Console.WriteLine("---- 8. goldens ----");
Golden("ShipRecord.hex", synthShips[0].ToBytes(), hash: false);
Golden("MissileRecord.hex", Frames.MissileRecordOf(missile).ToBytes(), hash: false);
Golden(
    "Input.hex",
    InputMessage
        .From(
            777,
            new ShipInputState
            {
                Thrust = 0.75f,
                Yaw = -1f,
                Firing = true,
                DropProbe = true,
                LockTargetId = 0x0102030405060708UL,
            }
        )
        .ToBytes(),
    hash: false
);
Golden(
    "Spawn.hex",
    new SpawnMessage
    {
        ShipClass = 3,
        LaunchBaseId = 0xB00B,
        Cargo = new[]
        {
            new CargoLoadDef { CargoId = 2, Count = 3 },
        },
        Mounts = new[]
        {
            new MountOverrideRecord { HpIndex = 1, WeaponId = uint.MaxValue },
        },
    }.ToBytes(),
    hash: false
);
Golden(
    "Hello.hex",
    new HelloMessage
    {
        Secret = "s",
        Name = "n",
        ReconnectToken = "t",
        JoinToken = "j",
    }.ToBytes(),
    hash: false
);
Golden("Welcome.sha", synthWelcome.ToBytes());
Golden("Snapshot.sha", synthSnapshot);
Golden("Defs.sha", synthDefsBytes);
Golden("TeamState.sha", synthTeamState.ToBytes());
Golden("MapList.sha", synthMaps.ToBytes());
Golden("LobbyState.sha", synthLobby);
Golden("MatchStats.sha", synthStats);
Golden("Contacts.sha", Frames.Contacts(vision).ToBytes());
Golden(
    "Minefields.sha",
    new MinefieldsMessage { AnchorSector = 3, Fields = new[] { Frames.MinefieldRecordOf(field) } }.ToBytes()
);
Golden("Salvage.sha", new SalvageMessage { AnchorSector = 5, Items = new[] { Frames.SalvageRecordOf(item, 1) } }.ToBytes());
Golden("Probes.sha", new ProbesMessage { Probes = new[] { Frames.ProbeRecordOf(probe, 10) } }.ToBytes());
Golden(
    "ShipLoadout.sha",
    new ShipLoadoutMessage
    {
        Ships = new[]
        {
            new ShipLoadoutRecord
            {
                ShipId = 1,
                WeaponIds = new uint[] { 0, uint.MaxValue },
                Hold = new[]
                {
                    new HoldItemRecord
                    {
                        Kind = 2,
                        ItemId = 3,
                        Count = 6,
                    },
                },
            },
        },
    }.ToBytes()
);
Golden(
    "ResearchState.sha",
    new ResearchStateMessage
    {
        Bases = new[]
        {
            new BaseResearchRecord
            {
                BaseId = 1,
                Active = new[]
                {
                    new ResearchActiveRecord
                    {
                        DevIndex = 3,
                        StartTick = 100,
                        DurationTicks = 400,
                    },
                },
                OnDeck = 9,
            },
        },
    }.ToBytes()
);
Golden(
    "ConstructorState.sha",
    new ConstructorStateMessage
    {
        Constructors = new[]
        {
            new ConstructorStateRecord
            {
                Id = 1,
                StationTypeId = 2,
                State = 5,
                StartTick = 10,
                DurationTicks = 20,
                TargetId = 30,
                ProducesMiner = true,
                LaunchBaseId = 40,
                ShipId = 50,
            },
        },
    }.ToBytes()
);
Golden(
    "Gone.sha",
    new MissileGoneMessage
    {
        Id = 0x1234,
        Reason = 1,
        Sector = 4,
        Pos = gonePos,
    }
        .ToBytes()
        .Concat(
            new SalvageGoneMessage
            {
                Id = item.Id,
                Reason = 2,
                Sector = 5,
                Pos = gonePos,
                ByShipId = 0xABCDEF0123UL,
            }.ToBytes()
        )
        .ToArray()
);

if (printGoldens)
{
    Console.WriteLine();
    Console.WriteLine("// ---- paste into Goldens.Table ----");
    foreach (var (n, v) in computedGoldens)
        Console.WriteLine($"        [\"{n}\"] = \"{v}\",");
}

Console.WriteLine();
Console.WriteLine(failures == 0 ? "ALL PASS" : $"{failures} FAILURE(S)");
return failures == 0 ? 0 : 1;

// Pinned layouts. Regenerate with `dotnet run --project tests/WireTest -- --print-goldens` ONLY when a
// layout change is intended (and Wire.ProtocolVersion was bumped).
static class Goldens
{
    public static readonly Dictionary<string, string> Table = new()
    {
        ["ShipRecord.hex"] =
            "88776655443322110001000700900118FCE02EDEAEA5E4404A80C2191400B8003D0040003A2A507855204A40E2010008E2010006AA03020104",
        ["MissileRecord.hex"] = "1807F6E5D4C3B2A103000000010C003EED84009D0FB05C00CD80459900000000000000",
        ["Input.hex"] = "02090300000000403F0000000000000000000080BF0000000000000000210807060504030201",
        ["Spawn.hex"] = "04030BB00000000000000102000000030101FFFFFFFF",
        ["Hello.hex"] = "010173016E017401006A",
        ["Welcome.sha"] = "7F14443FC9C31349AEB7EE1FAD7EC40374C31124D7580A03B1D32FC3A8F10C01",
        ["Snapshot.sha"] = "843FFB3326D288885FA604E11BC0DAEB9CAE6D15A0B697A316FF0F42166C6E9F",
        ["Defs.sha"] = "788C0B6B5DB71F2F274DA8577072ABDA338AC8AF019BC3EB7751ECEA6C8AB799",
        ["TeamState.sha"] = "25235899FBC33C1A257D7B77EAEAE952505462B4646ECB87A97839F338E447AE",
        ["MapList.sha"] = "F769D835423E744FA13F3CDC7D3D9EC75F04237A3D22D015A5C95724EB7986E1",
        ["LobbyState.sha"] = "4B0A27B18C1D18069B72B844B39215B352BFA8041C7EEA6285A0E88AA87ADA0B", // team rows (MsgLobbyState)
        ["MatchStats.sha"] = "BE3A951973FEA7F5A5D911BA99AA79E2DB1E46A2DCD40A6E1B134C252DACC5EE",
        ["Contacts.sha"] = "4D8FBDF13AC8A886E7930233D5FDEA0833F3D0B7D9C572F56986BFD5D5DDB9B4",
        ["Minefields.sha"] = "D2373973B1AE71B791C4982E628ECB480C3082E506167F52E8242E3BAFFA9137",
        ["Salvage.sha"] = "662E2256144D77C491EAD5CF39E3D5B0AAD6CA7ADCDE5295FF1C740E991E8CCB",
        ["Probes.sha"] = "37D850ABA44223163079AD407EF3ED07726567CFDCF710F15E311BC086D6CCA6",
        ["ShipLoadout.sha"] = "E25830D434802BBDC3274934EF42363535C1C00DC985528F16EAF115FDD80F3C",
        ["ResearchState.sha"] = "1E67F5C4D26E391B7E9BD73FB76C2D2216C7C3F08B8772F7FF6B96BC5C45C2F8",
        ["ConstructorState.sha"] = "5C9343E66F44F0303D3F519D85F8A7D5A873EF0AB3B147798745503BED27AAA9",
        ["Gone.sha"] = "E7FB379DD828E264574FC8CFE836AFD98BA348B3FCF23F9643DE7AE4CFAAD4A3",
    };
}
