using Godot;

// Installs the Stellar Allegiance mouse cursors (angular cyan pointer + matching I-beam)
// over the OS defaults. Art is generated by tools/cursor-gen/gen_cursor.py — regenerate
// there rather than editing the PNGs; the Arrow hotspot below must match the tip
// coordinate authored in that script.
public static class UiCursor
{
    public static void Apply()
    {
        var arrow = GD.Load<Texture2D>("res://assets/ui/cursor.png");
        var ibeam = GD.Load<Texture2D>("res://assets/ui/cursor_ibeam.png");
        if (arrow != null)
            Input.SetCustomMouseCursor(arrow, Input.CursorShape.Arrow, new Vector2(2, 2));
        if (ibeam != null)
            Input.SetCustomMouseCursor(ibeam, Input.CursorShape.Ibeam, new Vector2(16, 16));
    }
}
