using Godot;

// Installs the Stellar Allegiance mouse cursors (angular cyan pointer + matching I-beam)
// over the OS defaults. Art is generated by tools/cursor-gen/gen_cursor.py — regenerate
// there rather than editing the PNGs; the Arrow hotspot below must match the tip
// coordinate authored in that script.
public static class UiCursor
{
    public static void Apply()
    {
        var arrow = GD.Load<Texture2D>("res://assets/ui/cursor.png");
        var ibeam = GD.Load<Texture2D>("res://assets/ui/cursor_ibeam.png");
        if (arrow != null)
            Input.SetCustomMouseCursor(arrow, Input.CursorShape.Arrow, new Vector2(2, 2));
        if (ibeam != null)
            Input.SetCustomMouseCursor(ibeam, Input.CursorShape.Ibeam, new Vector2(16, 16));
    }

    // Hands the OS cursors back. The display server keeps a reference to every custom cursor image, and
    // Godot tears the display server down AFTER the rendering server — so an image still installed at
    // quit is freed with no renderer left to free it into: two "RenderingServer::get_singleton() is
    // null" errors from ~CompressedTexture2D plus leaked-texture-RID lines on EVERY exit, clean or not.
    // Run it as the scene tree goes away: both servers are still alive then.
    public static void Clear()
    {
        Input.SetCustomMouseCursor(null, Input.CursorShape.Arrow);
        Input.SetCustomMouseCursor(null, Input.CursorShape.Ibeam);
    }
}
