using SimServer.Sim;
using StellarAllegiance.Shared;
using StellarAllegiance.Shared.Net;

namespace SimServer.Net;

// The server's protocol facade. The wire LAYOUTS live on the shared frame types
// (shared/Net/Messages.cs, Records.cs — codecs generated by tools/wire-gen, see
// docs/adr/0003-wire-format-source-generator.md); the FILLS from sim/world/content state live in
// Frames.cs. This class is the byte-level API the hub and the test suites call: message ids, flag
// bits and record sizes aliased from the shared types, plus Build*/Write* wrappers that fill a frame
// and serialize it. Nothing here defines a byte position.
//
// Versioning: Wire.ProtocolVersion (shared) is checked by the client in the Welcome handshake; bump
// it whenever a frame layout changes (tests/WireTest's goldens fail loudly when one does).
public static class Protocol
{
    public const byte Version = Wire.ProtocolVersion;

    // Sentinel team byte for a pilot who hasn't picked a side ("NOAT" — not on a team). It travels on
    // the wire anywhere a team byte does and never indexes a real team array.
    public const byte NoTeam = Wire.NoTeam;

    // ---- fixed record sizes (the hub strides its per-tick scratch buffers by these) ----
    public const int ShipRecordSize = ShipRecord.Size;
    public const int MissileRecordSize = MissileRecord.Size;
    public const int MinefieldRecordSize = MinefieldRecord.Size;
    public const int ContactRecordSize = ContactRecord.Size;
    public const int ProbeRecordSize = ProbeRecord.Size;
    public const int SalvageRecordSize = SalvageRecord.Size;
    public const int RockUpdateRecordSize = RockUpdateRecord.Size;
    public const int MinerTargetRecordSize = MinerTargetRecord.Size;
    public const int ConstructorBuildRecordSize = ConstructorBuildRecord.Size;

    // ---- client -> server ----
    public const byte MsgHello = HelloMessage.MsgId;
    public const byte MsgInput = InputMessage.MsgId;
    public const byte MsgPing = PingMessage.MsgId;
    public const byte MsgSpawn = SpawnMessage.MsgId;
    public const byte MsgSetTeam = SetTeamMessage.MsgId;
    public const byte MsgSetReady = SetReadyMessage.MsgId;
    public const byte MsgChat = ChatMessage.MsgId;
    public const byte MsgBye = ByeMessage.MsgId;
    public const byte MsgSetTeamName = SetTeamNameMessage.MsgId;
    public const byte MsgSetMap = SetMapMessage.MsgId;
    public const byte MsgSetAutopilot = SetAutopilotMessage.MsgId;
    public const byte MsgOrder = OrderMessage.MsgId;
    public const byte MsgResearch = ResearchMessage.MsgId;
    public const byte MsgBuildConstructor = BuildConstructorMessage.MsgId;
    public const byte MsgConstructorCancel = ConstructorCancelMessage.MsgId;
    public const byte MsgBuyMiner = BuyMinerMessage.MsgId;

    // ---- server -> client ----
    public const byte MsgWelcome = WelcomeMessage.MsgId;
    public const byte MsgYouAre = YouAreMessage.MsgId;
    public const byte MsgSnapshot = SnapshotMessage.MsgId;
    public const byte MsgShipGone = ShipGoneMessage.MsgId;
    public const byte MsgBases = BasesMessage.MsgId;
    public const byte MsgPong = PongMessage.MsgId;
    public const byte MsgDefs = DefsMessage.MsgId;
    public const byte MsgLobbyState = LobbyStateMessage.MsgId;
    public const byte MsgChatRelay = ChatRelayMessage.MsgId;
    public const byte MsgTeamState = TeamStateMessage.MsgId;
    public const byte MsgMissiles = MissilesMessage.MsgId;
    public const byte MsgMissileGone = MissileGoneMessage.MsgId;
    public const byte MsgMinefields = MinefieldsMessage.MsgId;
    public const byte MsgMineGone = MineGoneMessage.MsgId;
    public const byte MsgChaff = ChaffMessage.MsgId;
    public const byte MsgReveal = RevealMessage.MsgId;
    public const byte MsgContacts = ContactsMessage.MsgId;
    public const byte MsgProbes = ProbesMessage.MsgId;
    public const byte MsgProbeGone = ProbeGoneMessage.MsgId;
    public const byte MsgMapList = MapListMessage.MsgId;
    public const byte MsgReject = RejectMessage.MsgId;
    public const byte MsgRockUpdate = RockUpdateMessage.MsgId;
    public const byte MsgMinerTargets = MinerTargetsMessage.MsgId;
    public const byte MsgResearchState = ResearchStateMessage.MsgId;
    public const byte MsgConstructorBuilds = ConstructorBuildsMessage.MsgId;
    public const byte MsgConstructorState = ConstructorStateMessage.MsgId;
    public const byte MsgRockGone = RockGoneMessage.MsgId;
    public const byte MsgShipLoadout = ShipLoadoutMessage.MsgId;
    public const byte MsgMatchStats = MatchStatsMessage.MsgId;
    public const byte MsgSalvage = SalvageMessage.MsgId;
    public const byte MsgSalvageGone = SalvageGoneMessage.MsgId;

    // ---- MsgInput flags byte ----
    public const byte FlagFiring = InputFlags.Firing;
    public const byte FlagBoost = InputFlags.Boost;
    public const byte FlagFiring2 = InputFlags.Firing2;
    public const byte FlagDropChaff = InputFlags.DropChaff;
    public const byte FlagDropMine = InputFlags.DropMine;
    public const byte FlagDropProbe = InputFlags.DropProbe;

    // ---- ship-record flags byte ----
    public const byte ShipFlagPig = ShipFlags.Pig;
    public const byte ShipFlagPod = ShipFlags.Pod;
    public const byte ShipFlagLockingMe = ShipFlags.LockingMe;
    public const byte ShipFlagLockedMe = ShipFlags.LockedMe;
    public const byte ShipFlagAutopilot = ShipFlags.Autopilot;
    public const byte ShipFlagMiner = ShipFlags.Miner;
    public const byte ShipFlagMining = ShipFlags.Mining;
    public const byte ShipFlagConstructor = ShipFlags.Constructor;

    // ---- fog reveal slice caps / rock-update chunking ----
    public const int RevealMaxBases = Frames.RevealMaxBases;
    public const int RevealMaxRocks = Frames.RevealMaxRocks;
    public const int RevealMaxAlephs = Frames.RevealMaxAlephs;
    public const int RevealMaxSectors = Frames.RevealMaxSectors;
    public const int RockUpdateMaxPerFrame = Frames.RockUpdateMaxPerFrame;

    // One pilot's scoreboard row. Name + Team ride the row rather than being looked up from the
    // lobby: a departed pilot loses BOTH server-side, and the end-of-match board still has to name
    // them. Connected is what the client renders as the "LEFT" badge.
    public readonly record struct StatsEntry(
        int Id,
        string Name,
        byte Team,
        bool Connected,
        int Kills,
        int Deaths,
        int Ejects,
        int Points
    );

    // ---- per-tick record writers (into the hub's scratch buffers) ----

    public static void WriteShip(Span<byte> dst, Simulation.ShipSim s) => Frames.ShipRecordOf(s).Write(dst);

    public static void WriteMissile(Span<byte> dst, Simulation.MissileSim m) => Frames.MissileRecordOf(m).Write(dst);

    public static void WriteMinefield(Span<byte> dst, Simulation.MineFieldSim f) => Frames.MinefieldRecordOf(f).Write(dst);

    public static void WriteProbe(Span<byte> dst, Simulation.ProbeSim p, uint tick) =>
        Frames.ProbeRecordOf(p, tick).Write(dst);

    public static void WriteSalvage(Span<byte> dst, Simulation.SalvageSim it, uint tick) =>
        Frames.SalvageRecordOf(it, tick).Write(dst);

    // ---- one-shot event frames ----

    public static byte[] BuildMissileGone(ulong id, byte reason, uint sector, Vec3 pos) =>
        new MissileGoneMessage
        {
            Id = id,
            Reason = reason,
            Sector = (ushort)sector,
            Pos = pos,
        }.ToBytes();

    public static byte[] BuildChaff(Simulation.ChaffSim c) => Frames.ChaffOf(c).ToBytes();

    public static byte[] BuildMineGone(ulong fieldId, byte mineIndex, byte reason, uint sector, Vec3 pos) =>
        new MineGoneMessage
        {
            FieldId = fieldId,
            MineIndex = mineIndex,
            Reason = reason,
            Sector = (ushort)sector,
            Pos = pos,
        }.ToBytes();

    public static byte[] BuildProbeGone(ulong id, byte reason, uint sector, Vec3 pos) =>
        new ProbeGoneMessage
        {
            Id = id,
            Reason = reason,
            Sector = (ushort)sector,
            Pos = pos,
        }.ToBytes();

    public static byte[] BuildSalvageGone(ulong id, byte reason, uint sector, Vec3 pos, ulong byShipId) =>
        new SalvageGoneMessage
        {
            Id = id,
            Reason = reason,
            Sector = (ushort)sector,
            Pos = pos,
            ByShipId = byShipId,
        }.ToBytes();

    public static byte[] BuildYouAre(ulong shipId) => new YouAreMessage { ShipId = shipId }.ToBytes();

    public static byte[] BuildShipGone(ulong shipId, byte reason) =>
        new ShipGoneMessage { ShipId = shipId, Reason = reason }.ToBytes();

    public static byte[] BuildPong(uint nonce) => new PongMessage { Nonce = nonce }.ToBytes();

    public static byte[] BuildChatRelay(byte scope, byte fromTeam, string name, string text) =>
        Frames.ChatRelay(scope, fromTeam, name, text).ToBytes();

    // ---- world statics / fog ----

    public static byte[] BuildWelcome(
        int clientId,
        byte team,
        World world,
        uint tick,
        byte[] reconnectToken,
        bool fog,
        Simulation.TeamVision? vision = null
    ) => Frames.Welcome(clientId, team, world, tick, reconnectToken, fog, vision).ToBytes();

    public static byte[]? BuildRevealSlice(
        World world,
        Simulation.TeamVision vision,
        IReadOnlyDictionary<ulong, int> rockIndex,
        int baseCur,
        int rockCur,
        int alephCur,
        int sectorCur,
        out int nextBase,
        out int nextRock,
        out int nextAleph,
        out int nextSector
    ) =>
        Frames
            .RevealSlice(
                world,
                vision,
                rockIndex,
                baseCur,
                rockCur,
                alephCur,
                sectorCur,
                out nextBase,
                out nextRock,
                out nextAleph,
                out nextSector
            )
            ?.ToBytes();

    public static byte[]? BuildBaseReveal(World world, IReadOnlyList<ulong> baseIds) =>
        Frames.BaseReveal(world, baseIds)?.ToBytes();

    public static byte[] BuildContacts(Simulation.TeamVision vision) => Frames.Contacts(vision).ToBytes();

    public static byte[] BuildBases(World world) => Frames.Bases(world).ToBytes();

    public static byte[] BuildBasesFor(World world, Simulation.TeamVision? vision) =>
        Frames.BasesFor(world, vision).ToBytes();

    // ---- low-rate state ----

    public static byte[] BuildTeamState(Simulation sim) => Frames.TeamState(sim).ToBytes();

    public static byte[] BuildResearchStateFor(World world, byte team) => Frames.ResearchStateFor(world, team).ToBytes();

    public static byte[] BuildConstructorState(Simulation sim, byte team) => Frames.ConstructorState(sim, team).ToBytes();

    public static List<byte[]> BuildRockUpdates(World world, IReadOnlyList<ulong> ids) =>
        Frames.RockUpdates(world, ids).ConvertAll(m => m.ToBytes());

    public static List<byte[]> BuildRockUpdatesFor(
        World world,
        Simulation.TeamVision? vision,
        IReadOnlyCollection<ulong> changedIds
    ) => Frames.RockUpdatesFor(world, vision, changedIds).ConvertAll(m => m.ToBytes());

    public static byte[]? BuildRockGone(IReadOnlyCollection<ulong> ids) => Frames.RockGone(ids)?.ToBytes();

    public static byte[]? BuildMinerTargets(Simulation sim) => Frames.MinerTargets(sim)?.ToBytes();

    public static byte[] BuildShipLoadouts(Simulation sim) => Frames.ShipLoadouts(sim).ToBytes();

    public static byte[]? BuildConstructorBuilds(Simulation sim) => Frames.ConstructorBuilds(sim)?.ToBytes();

    // ---- once-per-connection + lobby ----

    public static byte[] BuildDefs(SimServer.Content.ContentSet content) => Frames.Defs(content).ToBytes();

    public static byte[] BuildLobbyState(
        byte phase,
        byte winner,
        IReadOnlyList<LobbyEntry> entries,
        string team0Name,
        string team1Name,
        int hostId,
        string selectedMap,
        int commander0,
        int commander1
    ) =>
        Frames
            .LobbyState(phase, winner, entries, team0Name, team1Name, hostId, selectedMap, commander0, commander1)
            .ToBytes();

    public static byte[] BuildMatchStats(
        IReadOnlyList<StatsEntry> pilots,
        IReadOnlyList<(byte Team, int Garrisons, int Outposts)> teams
    ) => Frames.MatchStats(pilots, teams).ToBytes();

    public static byte[] BuildMapList(IReadOnlyList<SimServer.Content.MapCatalogEntry> maps) =>
        Frames.MapList(maps).ToBytes();
}
