// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ApplyInputHandler(ReducerEventContext ctx, float thrust, float strafeX, float strafeY, float yaw, float pitch, float roll, bool firing, uint clientTick);
        public event ApplyInputHandler? OnApplyInput;

        public void ApplyInput(float thrust, float strafeX, float strafeY, float yaw, float pitch, float roll, bool firing, uint clientTick)
        {
            conn.InternalCallReducer(new Reducer.ApplyInput(thrust, strafeX, strafeY, yaw, pitch, roll, firing, clientTick));
        }

        public bool InvokeApplyInput(ReducerEventContext ctx, Reducer.ApplyInput args)
        {
            if (OnApplyInput == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnApplyInput(
                ctx,
                args.Thrust,
                args.StrafeX,
                args.StrafeY,
                args.Yaw,
                args.Pitch,
                args.Roll,
                args.Firing,
                args.ClientTick
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ApplyInput : Reducer, IReducerArgs
        {
            [DataMember(Name = "thrust")]
            public float Thrust;
            [DataMember(Name = "strafe_x")]
            public float StrafeX;
            [DataMember(Name = "strafe_y")]
            public float StrafeY;
            [DataMember(Name = "yaw")]
            public float Yaw;
            [DataMember(Name = "pitch")]
            public float Pitch;
            [DataMember(Name = "roll")]
            public float Roll;
            [DataMember(Name = "firing")]
            public bool Firing;
            [DataMember(Name = "client_tick")]
            public uint ClientTick;

            public ApplyInput(
                float Thrust,
                float StrafeX,
                float StrafeY,
                float Yaw,
                float Pitch,
                float Roll,
                bool Firing,
                uint ClientTick
            )
            {
                this.Thrust = Thrust;
                this.StrafeX = StrafeX;
                this.StrafeY = StrafeY;
                this.Yaw = Yaw;
                this.Pitch = Pitch;
                this.Roll = Roll;
                this.Firing = Firing;
                this.ClientTick = ClientTick;
            }

            public ApplyInput()
            {
            }

            string IReducerArgs.ReducerName => "apply_input";
        }
    }
}
