// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void JoinTeamHandler(ReducerEventContext ctx, byte team);
        public event JoinTeamHandler? OnJoinTeam;

        public void JoinTeam(byte team)
        {
            conn.InternalCallReducer(new Reducer.JoinTeam(team));
        }

        public bool InvokeJoinTeam(ReducerEventContext ctx, Reducer.JoinTeam args)
        {
            if (OnJoinTeam == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnJoinTeam(
                ctx,
                args.Team
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class JoinTeam : Reducer, IReducerArgs
        {
            [DataMember(Name = "team")]
            public byte Team;

            public JoinTeam(byte Team)
            {
                this.Team = Team;
            }

            public JoinTeam()
            {
            }

            string IReducerArgs.ReducerName => "join_team";
        }
    }
}
