// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void QuickJoinHandler(ReducerEventContext ctx);
        public event QuickJoinHandler? OnQuickJoin;

        public void QuickJoin()
        {
            conn.InternalCallReducer(new Reducer.QuickJoin());
        }

        public bool InvokeQuickJoin(ReducerEventContext ctx, Reducer.QuickJoin args)
        {
            if (OnQuickJoin == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnQuickJoin(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class QuickJoin : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "quick_join";
        }
    }
}
