// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RegenerateWorldHandler(ReducerEventContext ctx, ulong seed);
        public event RegenerateWorldHandler? OnRegenerateWorld;

        public void RegenerateWorld(ulong seed)
        {
            conn.InternalCallReducer(new Reducer.RegenerateWorld(seed));
        }

        public bool InvokeRegenerateWorld(ReducerEventContext ctx, Reducer.RegenerateWorld args)
        {
            if (OnRegenerateWorld == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRegenerateWorld(
                ctx,
                args.Seed
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RegenerateWorld : Reducer, IReducerArgs
        {
            [DataMember(Name = "seed")]
            public ulong Seed;

            public RegenerateWorld(ulong Seed)
            {
                this.Seed = Seed;
            }

            public RegenerateWorld()
            {
            }

            string IReducerArgs.ReducerName => "regenerate_world";
        }
    }
}
