// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ReportMatchResultHandler(ReducerEventContext ctx, byte winner);
        public event ReportMatchResultHandler? OnReportMatchResult;

        public void ReportMatchResult(byte winner)
        {
            conn.InternalCallReducer(new Reducer.ReportMatchResult(winner));
        }

        public bool InvokeReportMatchResult(ReducerEventContext ctx, Reducer.ReportMatchResult args)
        {
            if (OnReportMatchResult == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnReportMatchResult(
                ctx,
                args.Winner
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ReportMatchResult : Reducer, IReducerArgs
        {
            [DataMember(Name = "winner")]
            public byte Winner;

            public ReportMatchResult(byte Winner)
            {
                this.Winner = Winner;
            }

            public ReportMatchResult()
            {
            }

            string IReducerArgs.ReducerName => "report_match_result";
        }
    }
}
