// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RespawnHandler(ReducerEventContext ctx, SpacetimeDB.Types.ShipClass shipClass);
        public event RespawnHandler? OnRespawn;

        public void Respawn(SpacetimeDB.Types.ShipClass shipClass)
        {
            conn.InternalCallReducer(new Reducer.Respawn(shipClass));
        }

        public bool InvokeRespawn(ReducerEventContext ctx, Reducer.Respawn args)
        {
            if (OnRespawn == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRespawn(
                ctx,
                args.ShipClass
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Respawn : Reducer, IReducerArgs
        {
            [DataMember(Name = "ship_class")]
            public ShipClass ShipClass;

            public Respawn(ShipClass ShipClass)
            {
                this.ShipClass = ShipClass;
            }

            public Respawn()
            {
            }

            string IReducerArgs.ReducerName => "respawn";
        }
    }
}
