// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SendChatHandler(ReducerEventContext ctx, string text, bool teamOnly);
        public event SendChatHandler? OnSendChat;

        public void SendChat(string text, bool teamOnly)
        {
            conn.InternalCallReducer(new Reducer.SendChat(text, teamOnly));
        }

        public bool InvokeSendChat(ReducerEventContext ctx, Reducer.SendChat args)
        {
            if (OnSendChat == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSendChat(
                ctx,
                args.Text,
                args.TeamOnly
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SendChat : Reducer, IReducerArgs
        {
            [DataMember(Name = "text")]
            public string Text;
            [DataMember(Name = "team_only")]
            public bool TeamOnly;

            public SendChat(
                string Text,
                bool TeamOnly
            )
            {
                this.Text = Text;
                this.TeamOnly = TeamOnly;
            }

            public SendChat()
            {
                this.Text = "";
            }

            string IReducerArgs.ReducerName => "send_chat";
        }
    }
}
