// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetSimEndpointHandler(ReducerEventContext ctx, string url, string secret);
        public event SetSimEndpointHandler? OnSetSimEndpoint;

        public void SetSimEndpoint(string url, string secret)
        {
            conn.InternalCallReducer(new Reducer.SetSimEndpoint(url, secret));
        }

        public bool InvokeSetSimEndpoint(ReducerEventContext ctx, Reducer.SetSimEndpoint args)
        {
            if (OnSetSimEndpoint == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetSimEndpoint(
                ctx,
                args.Url,
                args.Secret
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetSimEndpoint : Reducer, IReducerArgs
        {
            [DataMember(Name = "url")]
            public string Url;
            [DataMember(Name = "secret")]
            public string Secret;

            public SetSimEndpoint(
                string Url,
                string Secret
            )
            {
                this.Url = Url;
                this.Secret = Secret;
            }

            public SetSimEndpoint()
            {
                this.Url = "";
                this.Secret = "";
            }

            string IReducerArgs.ReducerName => "set_sim_endpoint";
        }
    }
}
