// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpsertWorldConfigHandler(ReducerEventContext ctx, SpacetimeDB.Types.WorldConfig cfg);
        public event UpsertWorldConfigHandler? OnUpsertWorldConfig;

        public void UpsertWorldConfig(SpacetimeDB.Types.WorldConfig cfg)
        {
            conn.InternalCallReducer(new Reducer.UpsertWorldConfig(cfg));
        }

        public bool InvokeUpsertWorldConfig(ReducerEventContext ctx, Reducer.UpsertWorldConfig args)
        {
            if (OnUpsertWorldConfig == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpsertWorldConfig(
                ctx,
                args.Cfg
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpsertWorldConfig : Reducer, IReducerArgs
        {
            [DataMember(Name = "cfg")]
            public WorldConfig Cfg;

            public UpsertWorldConfig(WorldConfig Cfg)
            {
                this.Cfg = Cfg;
            }

            public UpsertWorldConfig()
            {
                this.Cfg = new();
            }

            string IReducerArgs.ReducerName => "upsert_world_config";
        }
    }
}
