// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpsertWeaponDefHandler(ReducerEventContext ctx, SpacetimeDB.Types.WeaponDef def);
        public event UpsertWeaponDefHandler? OnUpsertWeaponDef;

        public void UpsertWeaponDef(SpacetimeDB.Types.WeaponDef def)
        {
            conn.InternalCallReducer(new Reducer.UpsertWeaponDef(def));
        }

        public bool InvokeUpsertWeaponDef(ReducerEventContext ctx, Reducer.UpsertWeaponDef args)
        {
            if (OnUpsertWeaponDef == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpsertWeaponDef(
                ctx,
                args.Def
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpsertWeaponDef : Reducer, IReducerArgs
        {
            [DataMember(Name = "def")]
            public WeaponDef Def;

            public UpsertWeaponDef(WeaponDef Def)
            {
                this.Def = Def;
            }

            public UpsertWeaponDef()
            {
                this.Def = new();
            }

            string IReducerArgs.ReducerName => "upsert_weapon_def";
        }
    }
}
