// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpsertBaseDefHandler(ReducerEventContext ctx, SpacetimeDB.Types.BaseDef def);
        public event UpsertBaseDefHandler? OnUpsertBaseDef;

        public void UpsertBaseDef(SpacetimeDB.Types.BaseDef def)
        {
            conn.InternalCallReducer(new Reducer.UpsertBaseDef(def));
        }

        public bool InvokeUpsertBaseDef(ReducerEventContext ctx, Reducer.UpsertBaseDef args)
        {
            if (OnUpsertBaseDef == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpsertBaseDef(
                ctx,
                args.Def
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpsertBaseDef : Reducer, IReducerArgs
        {
            [DataMember(Name = "def")]
            public BaseDef Def;

            public UpsertBaseDef(BaseDef Def)
            {
                this.Def = Def;
            }

            public UpsertBaseDef()
            {
                this.Def = new();
            }

            string IReducerArgs.ReducerName => "upsert_base_def";
        }
    }
}
