// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpsertShipClassDefHandler(ReducerEventContext ctx, SpacetimeDB.Types.ShipClassDef def);
        public event UpsertShipClassDefHandler? OnUpsertShipClassDef;

        public void UpsertShipClassDef(SpacetimeDB.Types.ShipClassDef def)
        {
            conn.InternalCallReducer(new Reducer.UpsertShipClassDef(def));
        }

        public bool InvokeUpsertShipClassDef(ReducerEventContext ctx, Reducer.UpsertShipClassDef args)
        {
            if (OnUpsertShipClassDef == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpsertShipClassDef(
                ctx,
                args.Def
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpsertShipClassDef : Reducer, IReducerArgs
        {
            [DataMember(Name = "def")]
            public ShipClassDef Def;

            public UpsertShipClassDef(ShipClassDef Def)
            {
                this.Def = Def;
            }

            public UpsertShipClassDef()
            {
                this.Def = new();
            }

            string IReducerArgs.ReducerName => "upsert_ship_class_def";
        }
    }
}
