// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Aleph
    {
        [DataMember(Name = "aleph_id")]
        public ulong AlephId;
        [DataMember(Name = "sector_id")]
        public uint SectorId;
        [DataMember(Name = "partner_id")]
        public ulong PartnerId;
        [DataMember(Name = "dest_sector_id")]
        public uint DestSectorId;
        [DataMember(Name = "pos_x")]
        public float PosX;
        [DataMember(Name = "pos_y")]
        public float PosY;
        [DataMember(Name = "pos_z")]
        public float PosZ;

        public Aleph(
            ulong AlephId,
            uint SectorId,
            ulong PartnerId,
            uint DestSectorId,
            float PosX,
            float PosY,
            float PosZ
        )
        {
            this.AlephId = AlephId;
            this.SectorId = SectorId;
            this.PartnerId = PartnerId;
            this.DestSectorId = DestSectorId;
            this.PosX = PosX;
            this.PosY = PosY;
            this.PosZ = PosZ;
        }

        public Aleph()
        {
        }
    }
}
