// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Asteroid
    {
        [DataMember(Name = "asteroid_id")]
        public ulong AsteroidId;
        [DataMember(Name = "pos_x")]
        public float PosX;
        [DataMember(Name = "pos_y")]
        public float PosY;
        [DataMember(Name = "pos_z")]
        public float PosZ;
        [DataMember(Name = "radius")]
        public float Radius;

        public Asteroid(
            ulong AsteroidId,
            float PosX,
            float PosY,
            float PosZ,
            float Radius
        )
        {
            this.AsteroidId = AsteroidId;
            this.PosX = PosX;
            this.PosY = PosY;
            this.PosZ = PosZ;
            this.Radius = Radius;
        }

        public Asteroid()
        {
        }
    }
}
