// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Asteroid
    {
        [DataMember(Name = "asteroid_id")]
        public ulong AsteroidId;
        [DataMember(Name = "sector_id")]
        public uint SectorId;
        [DataMember(Name = "pos_x")]
        public float PosX;
        [DataMember(Name = "pos_y")]
        public float PosY;
        [DataMember(Name = "pos_z")]
        public float PosZ;
        [DataMember(Name = "radius")]
        public float Radius;
        [DataMember(Name = "variant")]
        public string Variant;
        [DataMember(Name = "rot_x")]
        public float RotX;
        [DataMember(Name = "rot_y")]
        public float RotY;
        [DataMember(Name = "rot_z")]
        public float RotZ;

        public Asteroid(
            ulong AsteroidId,
            uint SectorId,
            float PosX,
            float PosY,
            float PosZ,
            float Radius,
            string Variant,
            float RotX,
            float RotY,
            float RotZ
        )
        {
            this.AsteroidId = AsteroidId;
            this.SectorId = SectorId;
            this.PosX = PosX;
            this.PosY = PosY;
            this.PosZ = PosZ;
            this.Radius = Radius;
            this.Variant = Variant;
            this.RotX = RotX;
            this.RotY = RotY;
            this.RotZ = RotZ;
        }

        public Asteroid()
        {
            this.Variant = "";
        }
    }
}
