// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BaseDef
    {
        [DataMember(Name = "base_type_id")]
        public byte BaseTypeId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "radius")]
        public float Radius;
        [DataMember(Name = "max_health")]
        public float MaxHealth;
        [DataMember(Name = "hardpoints")]
        public System.Collections.Generic.List<HardpointDef> Hardpoints;

        public BaseDef(
            byte BaseTypeId,
            string Name,
            float Radius,
            float MaxHealth,
            System.Collections.Generic.List<HardpointDef> Hardpoints
        )
        {
            this.BaseTypeId = BaseTypeId;
            this.Name = Name;
            this.Radius = Radius;
            this.MaxHealth = MaxHealth;
            this.Hardpoints = Hardpoints;
        }

        public BaseDef()
        {
            this.Name = "";
            this.Hardpoints = new();
        }
    }
}
