// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Base
    {
        [DataMember(Name = "base_id")]
        public ulong BaseId;
        [DataMember(Name = "team")]
        public byte Team;
        [DataMember(Name = "pos_x")]
        public float PosX;
        [DataMember(Name = "pos_y")]
        public float PosY;
        [DataMember(Name = "pos_z")]
        public float PosZ;
        [DataMember(Name = "health")]
        public float Health;

        public Base(
            ulong BaseId,
            byte Team,
            float PosX,
            float PosY,
            float PosZ,
            float Health
        )
        {
            this.BaseId = BaseId;
            this.Team = Team;
            this.PosX = PosX;
            this.PosY = PosY;
            this.PosZ = PosZ;
            this.Health = Health;
        }

        public Base()
        {
        }
    }
}
