// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ChatMessage
    {
        [DataMember(Name = "message_id")]
        public ulong MessageId;
        [DataMember(Name = "sender")]
        public SpacetimeDB.Identity Sender;
        [DataMember(Name = "sender_name")]
        public string SenderName;
        [DataMember(Name = "scope")]
        public byte Scope;
        [DataMember(Name = "team")]
        public byte Team;
        [DataMember(Name = "recipient")]
        public SpacetimeDB.Identity Recipient;
        [DataMember(Name = "is_system")]
        public bool IsSystem;
        [DataMember(Name = "text")]
        public string Text;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;

        public ChatMessage(
            ulong MessageId,
            SpacetimeDB.Identity Sender,
            string SenderName,
            byte Scope,
            byte Team,
            SpacetimeDB.Identity Recipient,
            bool IsSystem,
            string Text,
            SpacetimeDB.Timestamp CreatedAt
        )
        {
            this.MessageId = MessageId;
            this.Sender = Sender;
            this.SenderName = SenderName;
            this.Scope = Scope;
            this.Team = Team;
            this.Recipient = Recipient;
            this.IsSystem = IsSystem;
            this.Text = Text;
            this.CreatedAt = CreatedAt;
        }

        public ChatMessage()
        {
            this.SenderName = "";
            this.Text = "";
        }
    }
}
