// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class HardpointDef
    {
        [DataMember(Name = "kind")]
        public HardpointKind Kind;
        [DataMember(Name = "index")]
        public byte Index;
        [DataMember(Name = "off_x")]
        public float OffX;
        [DataMember(Name = "off_y")]
        public float OffY;
        [DataMember(Name = "off_z")]
        public float OffZ;
        [DataMember(Name = "dir_x")]
        public float DirX;
        [DataMember(Name = "dir_y")]
        public float DirY;
        [DataMember(Name = "dir_z")]
        public float DirZ;
        [DataMember(Name = "weapon_id")]
        public uint WeaponId;

        public HardpointDef(
            HardpointKind Kind,
            byte Index,
            float OffX,
            float OffY,
            float OffZ,
            float DirX,
            float DirY,
            float DirZ,
            uint WeaponId
        )
        {
            this.Kind = Kind;
            this.Index = Index;
            this.OffX = OffX;
            this.OffY = OffY;
            this.OffZ = OffZ;
            this.DirX = DirX;
            this.DirY = DirY;
            this.DirZ = DirZ;
            this.WeaponId = WeaponId;
        }

        public HardpointDef()
        {
        }
    }
}
