// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class JoinToken
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "team")]
        public byte Team;
        [DataMember(Name = "token")]
        public string Token;

        public JoinToken(
            SpacetimeDB.Identity Identity,
            byte Team,
            string Token
        )
        {
            this.Identity = Identity;
            this.Team = Team;
            this.Token = Token;
        }

        public JoinToken()
        {
            this.Token = "";
        }
    }
}
