// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Match
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "tick")]
        public uint Tick;
        [DataMember(Name = "phase")]
        public MatchPhase Phase;
        [DataMember(Name = "winner")]
        public byte? Winner;

        public Match(
            uint Id,
            uint Tick,
            MatchPhase Phase,
            byte? Winner
        )
        {
            this.Id = Id;
            this.Tick = Tick;
            this.Phase = Phase;
            this.Winner = Winner;
        }

        public Match()
        {
        }
    }
}
