// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Match
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "tick")]
        public uint Tick;
        [DataMember(Name = "phase")]
        public MatchPhase Phase;
        [DataMember(Name = "winner")]
        public byte? Winner;
        [DataMember(Name = "engaged_teams")]
        public byte EngagedTeams;
        [DataMember(Name = "seed")]
        public ulong Seed;
        [DataMember(Name = "last_tick_micros")]
        public long LastTickMicros;
        [DataMember(Name = "accum_micros")]
        public long AccumMicros;
        [DataMember(Name = "pigs_enabled")]
        public bool PigsEnabled;

        public Match(
            uint Id,
            uint Tick,
            MatchPhase Phase,
            byte? Winner,
            byte EngagedTeams,
            ulong Seed,
            long LastTickMicros,
            long AccumMicros,
            bool PigsEnabled
        )
        {
            this.Id = Id;
            this.Tick = Tick;
            this.Phase = Phase;
            this.Winner = Winner;
            this.EngagedTeams = EngagedTeams;
            this.Seed = Seed;
            this.LastTickMicros = LastTickMicros;
            this.AccumMicros = AccumMicros;
            this.PigsEnabled = PigsEnabled;
        }

        public Match()
        {
        }
    }
}
