// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Pig
    {
        [DataMember(Name = "pig_id")]
        public ulong PigId;
        [DataMember(Name = "team")]
        public byte Team;
        [DataMember(Name = "class")]
        public ShipClass Class;
        [DataMember(Name = "ship_id")]
        public ulong? ShipId;
        [DataMember(Name = "respawn_at_tick")]
        public uint RespawnAtTick;
        [DataMember(Name = "state")]
        public PigState State;
        [DataMember(Name = "target_ship_id")]
        public ulong? TargetShipId;

        public Pig(
            ulong PigId,
            byte Team,
            ShipClass Class,
            ulong? ShipId,
            uint RespawnAtTick,
            PigState State,
            ulong? TargetShipId
        )
        {
            this.PigId = PigId;
            this.Team = Team;
            this.Class = Class;
            this.ShipId = ShipId;
            this.RespawnAtTick = RespawnAtTick;
            this.State = State;
            this.TargetShipId = TargetShipId;
        }

        public Pig()
        {
        }
    }
}
