// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PigDecision
    {
        [DataMember(Name = "ship_id")]
        public ulong ShipId;
        [DataMember(Name = "pig_id")]
        public ulong PigId;
        [DataMember(Name = "kind")]
        public byte Kind;
        [DataMember(Name = "target_ship_id")]
        public ulong TargetShipId;
        [DataMember(Name = "px")]
        public float Px;
        [DataMember(Name = "py")]
        public float Py;
        [DataMember(Name = "pz")]
        public float Pz;
        [DataMember(Name = "radius")]
        public float Radius;
        [DataMember(Name = "decided_tick")]
        public uint DecidedTick;

        public PigDecision(
            ulong ShipId,
            ulong PigId,
            byte Kind,
            ulong TargetShipId,
            float Px,
            float Py,
            float Pz,
            float Radius,
            uint DecidedTick
        )
        {
            this.ShipId = ShipId;
            this.PigId = PigId;
            this.Kind = Kind;
            this.TargetShipId = TargetShipId;
            this.Px = Px;
            this.Py = Py;
            this.Pz = Pz;
            this.Radius = Radius;
            this.DecidedTick = DecidedTick;
        }

        public PigDecision()
        {
        }
    }
}
