// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PigSquad
    {
        [DataMember(Name = "team")]
        public byte Team;
        [DataMember(Name = "next_squad_tick")]
        public uint NextSquadTick;
        [DataMember(Name = "active")]
        public bool Active;

        public PigSquad(
            byte Team,
            uint NextSquadTick,
            bool Active
        )
        {
            this.Team = Team;
            this.NextSquadTick = NextSquadTick;
            this.Active = Active;
        }

        public PigSquad()
        {
        }
    }
}
