// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Player
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "team")]
        public byte? Team;
        [DataMember(Name = "ready")]
        public bool Ready;
        [DataMember(Name = "ship_id")]
        public ulong? ShipId;
        [DataMember(Name = "online")]
        public bool Online;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "chat_team")]
        public byte ChatTeam;

        public Player(
            SpacetimeDB.Identity Identity,
            byte? Team,
            bool Ready,
            ulong? ShipId,
            bool Online,
            string Name,
            byte ChatTeam
        )
        {
            this.Identity = Identity;
            this.Team = Team;
            this.Ready = Ready;
            this.ShipId = ShipId;
            this.Online = Online;
            this.Name = Name;
            this.ChatTeam = ChatTeam;
        }

        public Player()
        {
            this.Name = "";
        }
    }
}
