// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Projectile
    {
        [DataMember(Name = "projectile_id")]
        public ulong ProjectileId;
        [DataMember(Name = "team")]
        public byte Team;
        [DataMember(Name = "damage")]
        public float Damage;
        [DataMember(Name = "pos_x")]
        public float PosX;
        [DataMember(Name = "pos_y")]
        public float PosY;
        [DataMember(Name = "pos_z")]
        public float PosZ;
        [DataMember(Name = "vel_x")]
        public float VelX;
        [DataMember(Name = "vel_y")]
        public float VelY;
        [DataMember(Name = "vel_z")]
        public float VelZ;
        [DataMember(Name = "expires_at_tick")]
        public uint ExpiresAtTick;
        [DataMember(Name = "from_pig")]
        public bool FromPig;

        public Projectile(
            ulong ProjectileId,
            byte Team,
            float Damage,
            float PosX,
            float PosY,
            float PosZ,
            float VelX,
            float VelY,
            float VelZ,
            uint ExpiresAtTick,
            bool FromPig
        )
        {
            this.ProjectileId = ProjectileId;
            this.Team = Team;
            this.Damage = Damage;
            this.PosX = PosX;
            this.PosY = PosY;
            this.PosZ = PosZ;
            this.VelX = VelX;
            this.VelY = VelY;
            this.VelZ = VelZ;
            this.ExpiresAtTick = ExpiresAtTick;
            this.FromPig = FromPig;
        }

        public Projectile()
        {
        }
    }
}
