// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Sector
    {
        [DataMember(Name = "sector_id")]
        public uint SectorId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "center_x")]
        public float CenterX;
        [DataMember(Name = "center_y")]
        public float CenterY;
        [DataMember(Name = "center_z")]
        public float CenterZ;
        [DataMember(Name = "radius")]
        public float Radius;

        public Sector(
            uint SectorId,
            string Name,
            float CenterX,
            float CenterY,
            float CenterZ,
            float Radius
        )
        {
            this.SectorId = SectorId;
            this.Name = Name;
            this.CenterX = CenterX;
            this.CenterY = CenterY;
            this.CenterZ = CenterZ;
            this.Radius = Radius;
        }

        public Sector()
        {
            this.Name = "";
        }
    }
}
