// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Ship
    {
        [DataMember(Name = "ship_id")]
        public ulong ShipId;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "team")]
        public byte Team;
        [DataMember(Name = "class")]
        public ShipClass Class;
        [DataMember(Name = "pos_x")]
        public float PosX;
        [DataMember(Name = "pos_y")]
        public float PosY;
        [DataMember(Name = "pos_z")]
        public float PosZ;
        [DataMember(Name = "vel_x")]
        public float VelX;
        [DataMember(Name = "vel_y")]
        public float VelY;
        [DataMember(Name = "vel_z")]
        public float VelZ;
        [DataMember(Name = "rot_x")]
        public float RotX;
        [DataMember(Name = "rot_y")]
        public float RotY;
        [DataMember(Name = "rot_z")]
        public float RotZ;
        [DataMember(Name = "rot_w")]
        public float RotW;
        [DataMember(Name = "health")]
        public float Health;
        [DataMember(Name = "last_input_tick")]
        public uint LastInputTick;

        public Ship(
            ulong ShipId,
            SpacetimeDB.Identity Owner,
            byte Team,
            ShipClass Class,
            float PosX,
            float PosY,
            float PosZ,
            float VelX,
            float VelY,
            float VelZ,
            float RotX,
            float RotY,
            float RotZ,
            float RotW,
            float Health,
            uint LastInputTick
        )
        {
            this.ShipId = ShipId;
            this.Owner = Owner;
            this.Team = Team;
            this.Class = Class;
            this.PosX = PosX;
            this.PosY = PosY;
            this.PosZ = PosZ;
            this.VelX = VelX;
            this.VelY = VelY;
            this.VelZ = VelZ;
            this.RotX = RotX;
            this.RotY = RotY;
            this.RotZ = RotZ;
            this.RotW = RotW;
            this.Health = Health;
            this.LastInputTick = LastInputTick;
        }

        public Ship()
        {
        }
    }
}
