// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ShipClassDef
    {
        [DataMember(Name = "class_id")]
        public byte ClassId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "mass")]
        public float Mass;
        [DataMember(Name = "max_speed")]
        public float MaxSpeed;
        [DataMember(Name = "accel")]
        public float Accel;
        [DataMember(Name = "rate_yaw_deg")]
        public float RateYawDeg;
        [DataMember(Name = "rate_pitch_deg")]
        public float RatePitchDeg;
        [DataMember(Name = "rate_roll_deg")]
        public float RateRollDeg;
        [DataMember(Name = "drift_yaw_deg")]
        public float DriftYawDeg;
        [DataMember(Name = "drift_pitch_deg")]
        public float DriftPitchDeg;
        [DataMember(Name = "side_mult")]
        public float SideMult;
        [DataMember(Name = "back_mult")]
        public float BackMult;
        [DataMember(Name = "ab_accel")]
        public float AbAccel;
        [DataMember(Name = "ab_on_rate")]
        public float AbOnRate;
        [DataMember(Name = "ab_off_rate")]
        public float AbOffRate;
        [DataMember(Name = "max_hull")]
        public float MaxHull;
        [DataMember(Name = "hardpoints")]
        public System.Collections.Generic.List<HardpointDef> Hardpoints;
        [DataMember(Name = "faction_id")]
        public uint FactionId;

        public ShipClassDef(
            byte ClassId,
            string Name,
            float Mass,
            float MaxSpeed,
            float Accel,
            float RateYawDeg,
            float RatePitchDeg,
            float RateRollDeg,
            float DriftYawDeg,
            float DriftPitchDeg,
            float SideMult,
            float BackMult,
            float AbAccel,
            float AbOnRate,
            float AbOffRate,
            float MaxHull,
            System.Collections.Generic.List<HardpointDef> Hardpoints,
            uint FactionId
        )
        {
            this.ClassId = ClassId;
            this.Name = Name;
            this.Mass = Mass;
            this.MaxSpeed = MaxSpeed;
            this.Accel = Accel;
            this.RateYawDeg = RateYawDeg;
            this.RatePitchDeg = RatePitchDeg;
            this.RateRollDeg = RateRollDeg;
            this.DriftYawDeg = DriftYawDeg;
            this.DriftPitchDeg = DriftPitchDeg;
            this.SideMult = SideMult;
            this.BackMult = BackMult;
            this.AbAccel = AbAccel;
            this.AbOnRate = AbOnRate;
            this.AbOffRate = AbOffRate;
            this.MaxHull = MaxHull;
            this.Hardpoints = Hardpoints;
            this.FactionId = FactionId;
        }

        public ShipClassDef()
        {
            this.Name = "";
            this.Hardpoints = new();
        }
    }
}
