// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ShipInput
    {
        [DataMember(Name = "input_id")]
        public ulong InputId;
        [DataMember(Name = "ship_id")]
        public ulong ShipId;
        [DataMember(Name = "tick")]
        public uint Tick;
        [DataMember(Name = "thrust")]
        public float Thrust;
        [DataMember(Name = "strafe_x")]
        public float StrafeX;
        [DataMember(Name = "strafe_y")]
        public float StrafeY;
        [DataMember(Name = "yaw")]
        public float Yaw;
        [DataMember(Name = "pitch")]
        public float Pitch;
        [DataMember(Name = "roll")]
        public float Roll;
        [DataMember(Name = "firing")]
        public bool Firing;

        public ShipInput(
            ulong InputId,
            ulong ShipId,
            uint Tick,
            float Thrust,
            float StrafeX,
            float StrafeY,
            float Yaw,
            float Pitch,
            float Roll,
            bool Firing
        )
        {
            this.InputId = InputId;
            this.ShipId = ShipId;
            this.Tick = Tick;
            this.Thrust = Thrust;
            this.StrafeX = StrafeX;
            this.StrafeY = StrafeY;
            this.Yaw = Yaw;
            this.Pitch = Pitch;
            this.Roll = Roll;
            this.Firing = Firing;
        }

        public ShipInput()
        {
        }
    }
}
