// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ShotResolution
    {
        [DataMember(Name = "scheduled_id")]
        public ulong ScheduledId;
        [DataMember(Name = "scheduled_at")]
        public SpacetimeDB.ScheduleAt ScheduledAt;
        [DataMember(Name = "projectile_id")]
        public ulong ProjectileId;
        [DataMember(Name = "kind")]
        public ShotOutcomeKind Kind;
        [DataMember(Name = "target_id")]
        public ulong TargetId;
        [DataMember(Name = "damage")]
        public float Damage;

        public ShotResolution(
            ulong ScheduledId,
            SpacetimeDB.ScheduleAt ScheduledAt,
            ulong ProjectileId,
            ShotOutcomeKind Kind,
            ulong TargetId,
            float Damage
        )
        {
            this.ScheduledId = ScheduledId;
            this.ScheduledAt = ScheduledAt;
            this.ProjectileId = ProjectileId;
            this.Kind = Kind;
            this.TargetId = TargetId;
            this.Damage = Damage;
        }

        public ShotResolution()
        {
            this.ScheduledAt = null!;
        }
    }
}
