// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ShotResolution
    {
        [DataMember(Name = "shot_id")]
        public ulong ShotId;
        [DataMember(Name = "resolve_at_tick")]
        public uint ResolveAtTick;
        [DataMember(Name = "kind")]
        public ShotOutcomeKind Kind;
        [DataMember(Name = "target_id")]
        public ulong TargetId;
        [DataMember(Name = "damage")]
        public float Damage;

        public ShotResolution(
            ulong ShotId,
            uint ResolveAtTick,
            ShotOutcomeKind Kind,
            ulong TargetId,
            float Damage
        )
        {
            this.ShotId = ShotId;
            this.ResolveAtTick = ResolveAtTick;
            this.Kind = Kind;
            this.TargetId = TargetId;
            this.Damage = Damage;
        }

        public ShotResolution()
        {
        }
    }
}
