// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SimConfig
    {
        [DataMember(Name = "id")]
        public byte Id;
        [DataMember(Name = "secret")]
        public string Secret;

        public SimConfig(
            byte Id,
            string Secret
        )
        {
            this.Id = Id;
            this.Secret = Secret;
        }

        public SimConfig()
        {
            this.Secret = "";
        }
    }
}
