// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SimEndpoint
    {
        [DataMember(Name = "id")]
        public byte Id;
        [DataMember(Name = "url")]
        public string Url;

        public SimEndpoint(
            byte Id,
            string Url
        )
        {
            this.Id = Id;
            this.Url = Url;
        }

        public SimEndpoint()
        {
            this.Url = "";
        }
    }
}
