// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WeaponDef
    {
        [DataMember(Name = "weapon_id")]
        public uint WeaponId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "damage")]
        public float Damage;
        [DataMember(Name = "fire_interval_ticks")]
        public uint FireIntervalTicks;
        [DataMember(Name = "projectile_speed")]
        public float ProjectileSpeed;
        [DataMember(Name = "projectile_life_ticks")]
        public uint ProjectileLifeTicks;
        [DataMember(Name = "projectile_radius")]
        public float ProjectileRadius;
        [DataMember(Name = "spread_rad")]
        public float SpreadRad;

        public WeaponDef(
            uint WeaponId,
            string Name,
            float Damage,
            uint FireIntervalTicks,
            float ProjectileSpeed,
            uint ProjectileLifeTicks,
            float ProjectileRadius,
            float SpreadRad
        )
        {
            this.WeaponId = WeaponId;
            this.Name = Name;
            this.Damage = Damage;
            this.FireIntervalTicks = FireIntervalTicks;
            this.ProjectileSpeed = ProjectileSpeed;
            this.ProjectileLifeTicks = ProjectileLifeTicks;
            this.ProjectileRadius = ProjectileRadius;
            this.SpreadRad = SpreadRad;
        }

        public WeaponDef()
        {
            this.Name = "";
        }
    }
}
