// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WorldConfig
    {
        [DataMember(Name = "id")]
        public byte Id;
        [DataMember(Name = "sector_scale")]
        public float SectorScale;
        [DataMember(Name = "asteroid_density")]
        public float AsteroidDensity;
        [DataMember(Name = "debug_freeze_brain")]
        public bool DebugFreezeBrain;
        [DataMember(Name = "debug_no_fire")]
        public bool DebugNoFire;

        public WorldConfig(
            byte Id,
            float SectorScale,
            float AsteroidDensity,
            bool DebugFreezeBrain,
            bool DebugNoFire
        )
        {
            this.Id = Id;
            this.SectorScale = SectorScale;
            this.AsteroidDensity = AsteroidDensity;
            this.DebugFreezeBrain = DebugFreezeBrain;
            this.DebugNoFire = DebugNoFire;
        }

        public WorldConfig()
        {
        }
    }
}
